# Comprehensive kanji dictionary
# Format: kanji -> (han_viet, meaning, example_word, example_reading, example_meaning)

KANJI_DB = {
    "一": ("NHAT", "Một", "一日", "いちにち", "Một ngày"),
    "丁": ("DINH", "Đinh, đơn vị đếm", "丁寧", "ていねい", "Cẩn thận, lịch sự"),
    "七": ("THAT", "Bảy", "七月", "しちがつ", "Tháng bảy"),
    "大": ("DAI", "Lớn, to", "大学", "だいがく", "Đại học"),
    "三": ("TAM", "Ba", "三月", "さんがつ", "Tháng ba"),
    "上": ("THUONG", "Trên, lên", "上手", "じょうず", "Giỏi, khéo léo"),
    "下": ("HA", "Dưới, xuống", "下手", "へた", "Vụng về, kém"),
    "与": ("DU", "Cho, trao", "与える", "あたえる", "Cho, trao tặng"),
    "万": ("VAN", "Mười nghìn", "万円", "まんえん", "Mười nghìn yên"),
    "不": ("BAT", "Không, bất", "不安", "ふあん", "Lo lắng, bất an"),
    "且": ("CHA", "Hơn nữa, vả lại", "且つ", "かつ", "Vừa... vừa..."),
    "世": ("THE", "Thế giới, đời", "世界", "せかい", "Thế giới"),
    "両": ("LUONG", "Cả hai", "両親", "りょうしん", "Cha mẹ"),
    "並": ("BANG", "Song song, hàng", "並べる", "ならべる", "Xếp hàng"),
    "中": ("TRUNG", "Giữa, trong", "中学", "ちゅうがく", "Trung học cơ sở"),
    "丸": ("HOAN", "Tròn, viên", "丸い", "まるい", "Tròn"),
    "主": ("CHU", "Chủ, chính", "主人", "しゅじん", "Chồng, chủ nhà"),
    "久": ("CUU", "Lâu dài", "久しぶり", "ひさしぶり", "Lâu không gặp"),
    "乏": ("PHAP", "Thiếu, nghèo", "乏しい", "とぼしい", "Thiếu thốn"),
    "乗": ("THANG", "Lên (xe), cưỡi", "乗り物", "のりもの", "Phương tiện giao thông"),
    "九": ("CUU", "Chín", "九月", "くがつ", "Tháng chín"),
    "乳": ("NHU", "Sữa, vú", "牛乳", "ぎゅうにゅう", "Sữa bò"),
    "乾": ("CAN", "Khô", "乾燥", "かんそう", "Khô ráo, khô khan"),
    "乱": ("LOAN", "Loạn, rối loạn", "混乱", "こんらん", "Hỗn loạn"),
    "了": ("LIEU", "Kết thúc, xong", "終了", "しゅうりょう", "Kết thúc"),
    "予": ("DU", "Trước, dự", "予定", "よてい", "Kế hoạch, dự định"),
    "争": ("TRANH", "Tranh, đấu tranh", "戦争", "せんそう", "Chiến tranh"),
    "事": ("SU", "Việc, sự", "仕事", "しごと", "Công việc"),
    "二": ("NHI", "Hai", "二月", "にがつ", "Tháng hai"),
    "互": ("HO", "Lẫn nhau", "互いに", "たがいに", "Lẫn nhau"),
    "五": ("NGU", "Năm", "五月", "ごがつ", "Tháng năm"),
    "亡": ("VONG", "Mất, chết", "死亡", "しぼう", "Tử vong"),
    "交": ("GIAO", "Giao, qua lại", "交通", "こうつう", "Giao thông"),
    "京": ("KINH", "Kinh đô", "東京", "とうきょう", "Tokyo"),
    "人": ("NHAN", "Người", "人間", "にんげん", "Con người"),
    "今": ("KIM", "Bây giờ, hiện tại", "今日", "きょう", "Hôm nay"),
    "仏": ("PHAT", "Phật, Pháp", "仏教", "ぶっきょう", "Phật giáo"),
    "低": ("DE", "Thấp", "低い", "ひくい", "Thấp"),
    "似": ("TU", "Giống, tương tự", "似る", "にる", "Giống, trông giống"),
    "余": ("DU", "Dư, thừa", "余裕", "よゆう", "余裕, rộng rãi"),
    "同": ("DONG", "Cùng, đồng", "同じ", "おなじ", "Giống nhau"),
    "伸": ("THAN", "Vươn, duỗi", "背伸び", "せのび", "Kiễng chân"),
    "伴": ("BAN", "Bạn, đi cùng", "伴う", "ともなう", "Đi kèm, đi cùng"),
    "使": ("SU", "Dùng, sai khiến", "使い方", "つかいかた", "Cách sử dụng"),
    "例": ("LE", "Ví dụ, thí dụ", "例えば", "たとえば", "Ví dụ"),
    "価": ("GIA", "Giá, giá trị", "価格", "かかく", "Giá cả"),
    "供": ("CUNG", "Cung cấp, trẻ em", "子供", "こども", "Trẻ em"),
    "依": ("Y", "Nương tựa, y cứ", "依頼", "いらい", "Nhờ vả, yêu cầu"),
    "係": ("HE", "Quan hệ, liên hệ", "係員", "かかりいん", "Nhân viên phụ trách"),
    "信": ("TIN", "Tin tưởng, tín", "信じる", "しんじる", "Tin tưởng"),
    "便": ("TIEN", "Tiện lợi, thư từ", "便利", "べんり", "Tiện lợi"),
    "保": ("BAO", "Giữ, bảo đảm", "保険", "ほけん", "Bảo hiểm"),
    "倍": ("BỘI", "Gấp bội", "二倍", "にばい", "Gấp đôi"),
    "候": ("HAU", "Thời tiết, chờ đợi", "候補", "こうほ", "Ứng cử viên"),
    "借": ("TA", "Mượn, vay", "借りる", "かりる", "Mượn"),
    "倉": ("THUONG", "Kho, nhà kho", "倉庫", "そうこ", "Kho bãi"),
    "個": ("CA", "Cái, cá nhân", "個人", "こじん", "Cá nhân"),
    "介": ("GIOI", "Giới thiệu, trung gian", "紹介", "しょうかい", "Giới thiệu"),
    "仕": ("SI", "Làm việc, phục vụ", "仕事", "しごと", "Công việc"),
    "他": ("THA", "Khác, người khác", "他人", "たにん", "Người khác"),
    "代": ("DAI", "Thay thế, thế hệ", "時代", "じだい", "Thời đại"),
    "以": ("DI", "Bằng, với, từ", "以上", "いじょう", "Trên, hơn"),
    "付": ("PHU", "Gắn, đính kèm", "気付く", "きづく", "Chú ý, nhận ra"),
    "令": ("LENH", "Lệnh, mệnh lệnh", "命令", "めいれい", "Mệnh lệnh"),
    "休": ("NGHI", "Nghỉ ngơi", "休日", "きゅうじつ", "Ngày nghỉ"),
    "会": ("HOI", "Hội, gặp gỡ", "会社", "かいしゃ", "Công ty"),
    "仲": ("TRUNG", "Mối quan hệ, bạn bè", "仲間", "なかま", "Bạn bè, đồng nghiệp"),
    "伝": ("TRUYEN", "Truyền, chuyển", "伝える", "つたえる", "Truyền đạt"),
    "件": ("KIEN", "Vụ, kiện", "条件", "じょうけん", "Điều kiện"),
    "任": ("NHIEM", "Nhiệm vụ, giao phó", "責任", "せきにん", "Trách nhiệm"),
    "仰": ("NGƯỠNG", "Ngưỡng mộ, nhìn lên", "仰ぐ", "あおぐ", "Nhìn lên, ngưỡng vọng"),
    "伐": ("PHAT", "Đốn, chặt", "征伐", "せいばつ", "Chinh phạt"),
    "何": ("HO", "Cái gì, bao nhiêu", "何時", "なんじ", "Mấy giờ"),
    "作": ("TAC", "Làm, tạo ra", "作品", "さくひん", "Tác phẩm"),
    "体": ("THE", "Thân thể, cơ thể", "体力", "たいりょく", "Sức lực"),
    "住": ("TRU", "Ở, cư trú", "住所", "じゅうしょ", "Địa chỉ"),
    "位": ("VI", "Vị trí, cấp bậc", "地位", "ちい", "Địa vị"),
    "修": ("TU", "Tu sửa, học", "修理", "しゅうり", "Sửa chữa"),
    "値": ("TRI", "Giá trị, trị số", "値段", "ねだん", "Giá cả"),
    "俳": ("BAI", "Nghệ nhân, thơ haiku", "俳句", "はいく", "Thơ haiku"),
    "倒": ("DAO", "Ngã, lật ngược", "倒れる", "たおれる", "Ngã, đổ"),
    "健": ("KIEN", "Khỏe mạnh", "健康", "けんこう", "Sức khỏe"),
    "側": ("TAC", "Phía, bên cạnh", "右側", "みぎがわ", "Bên phải"),
    "停": ("DINH", "Dừng lại, đỗ", "停車", "ていしゃ", "Dừng xe"),
    "偶": ("NGU", "Ngẫu nhiên, cặp", "偶然", "ぐうぜん", "Ngẫu nhiên"),
    "備": ("BI", "Chuẩn bị", "準備", "じゅんび", "Chuẩn bị"),
    "偉": ("VI", "Vĩ đại, xuất sắc", "偉人", "いじん", "Vĩ nhân"),
    "傘": ("TAN", "Ô, dù", "傘", "かさ", "Ô dù"),
    "働": ("DONG", "Làm việc", "労働", "ろうどう", "Lao động"),
    "傷": ("THUONG", "Vết thương", "傷つく", "きずつく", "Bị tổn thương"),
    "傾": ("KHUYNH", "Nghiêng, xu hướng", "傾向", "けいこう", "Xu hướng"),
    "像": ("TUONG", "Hình ảnh, tượng", "想像", "そうぞう", "Tưởng tượng"),
    "僕": ("BOC", "Tôi (nam giới)", "僕たち", "ぼくたち", "Chúng tôi (nam)"),
    "僚": ("LIEU", "Đồng liêu, đồng nghiệp", "同僚", "どうりょう", "Đồng nghiệp"),
    "億": ("UC", "Trăm triệu", "億円", "おくえん", "Trăm triệu yên"),
    "儀": ("NGHI", "Nghi lễ, phép tắc", "儀式", "ぎしき", "Nghi lễ"),
    "優": ("UU", "Ưu, xuất sắc, dịu dàng", "優しい", "やさしい", "Dịu dàng"),
    "償": ("THUONG", "Bồi thường", "補償", "ほしょう", "Bồi thường"),
    "元": ("NGUYEN", "Gốc, nguyên", "元気", "げんき", "Khỏe mạnh, vui vẻ"),
    "兄": ("HUYNH", "Anh trai", "兄弟", "きょうだい", "Anh chị em"),
    "先": ("TIEN", "Trước, đầu tiên", "先生", "せんせい", "Giáo viên"),
    "光": ("QUANG", "Ánh sáng", "光る", "ひかる", "Sáng, chiếu sáng"),
    "充": ("SUNG", "Đầy đủ, sung mãn", "充電", "じゅうでん", "Sạc pin"),
    "児": ("NHI", "Trẻ em", "小児", "しょうに", "Nhi đồng"),
    "克": ("KHAC", "Khắc phục, vượt qua", "克服", "こくふく", "Khắc phục"),
    "免": ("MIEN", "Miễn, thoát", "免許", "めんきょ", "Giấy phép"),
    "入": ("NHAP", "Vào, nhập", "入学", "にゅうがく", "Nhập học"),
    "内": ("NOI", "Trong, nội", "内容", "ないよう", "Nội dung"),
    "全": ("TOAN", "Toàn, tất cả", "全部", "ぜんぶ", "Tất cả"),
    "八": ("BAT", "Tám", "八月", "はちがつ", "Tháng tám"),
    "公": ("CONG", "Công, công cộng", "公園", "こうえん", "Công viên"),
    "六": ("LUC", "Sáu", "六月", "ろくがつ", "Tháng sáu"),
    "共": ("CONG", "Cùng nhau, chung", "共通", "きょうつう", "Chung, phổ biến"),
    "具": ("CU", "Dụng cụ, đầy đủ", "道具", "どうぐ", "Dụng cụ, công cụ"),
    "典": ("DIEN", "Điển, mẫu mực", "辞典", "じてん", "Từ điển"),
    "円": ("VIEN", "Yên (tiền), tròn", "円高", "えんだか", "Đồng yên mạnh"),
    "冊": ("SACH", "Quyển, cuốn sách", "一冊", "いっさつ", "Một quyển"),
    "再": ("TAI", "Lại, tái", "再び", "ふたたび", "Lại, một lần nữa"),
    "冗": ("DUNG", "Thừa, vô ích", "冗談", "じょうだん", "Trò đùa"),
    "写": ("THA", "Chép, chụp", "写真", "しゃしん", "Ảnh chụp"),
    "冬": ("DONG", "Mùa đông", "冬休み", "ふゆやすみ", "Nghỉ đông"),
    "冷": ("LANH", "Lạnh", "冷蔵庫", "れいぞうこ", "Tủ lạnh"),
    "凍": ("DONG", "Đóng băng, đông cứng", "冷凍", "れいとう", "Đông lạnh"),
    "処": ("XU", "Nơi, xử lý", "処理", "しょり", "Xử lý"),
    "出": ("XUAT", "Ra, xuất", "出発", "しゅっぱつ", "Khởi hành"),
    "刀": ("DAO", "Dao, kiếm", "日本刀", "にほんとう", "Kiếm Nhật"),
    "切": ("THIET", "Cắt, quan trọng", "大切", "たいせつ", "Quan trọng"),
    "分": ("PHAN", "Phần, phút, hiểu", "自分", "じぶん", "Bản thân"),
    "列": ("LIET", "Hàng, liệt", "列車", "れっしゃ", "Đoàn tàu"),
    "刑": ("HINH", "Hình phạt", "刑事", "けいじ", "Thám tử, hình sự"),
    "初": ("SO", "Đầu tiên, ban đầu", "初めて", "はじめて", "Lần đầu tiên"),
    "別": ("BIET", "Tách, khác biệt", "別れる", "わかれる", "Chia tay"),
    "利": ("LOI", "Lợi ích, bén", "利用", "りよう", "Sử dụng, tận dụng"),
    "判": ("PHAN", "Phán xét, quyết định", "判断", "はんだん", "Phán đoán"),
    "刷": ("SUAT", "In, quét", "印刷", "いんさつ", "In ấn"),
    "券": ("PHIEU", "Vé, phiếu", "入場券", "にゅうじょうけん", "Vé vào cổng"),
    "制": ("CHE", "Chế độ, kiểm soát", "制度", "せいど", "Chế độ"),
    "刻": ("KHAC", "Khắc, thời điểm", "時刻", "じこく", "Thời khắc"),
    "刺": ("THICH", "Đâm, gai", "刺激", "しげき", "Kích thích"),
    "到": ("DAO", "Đến, tới", "到着", "とうちゃく", "Đến nơi"),
    "前": ("TIEN", "Trước, phía trước", "前後", "ぜんご", "Trước sau"),
    "則": ("TAC", "Quy tắc, luật tắc", "規則", "きそく", "Quy tắc"),
    "削": ("XUC", "Gọt, xóa", "削除", "さくじょ", "Xóa bỏ"),
    "剣": ("KIEM", "Kiếm", "剣道", "けんどう", "Kiếm đạo"),
    "剤": ("TE", "Thuốc, chế phẩm", "洗剤", "せんざい", "Chất tẩy rửa"),
    "副": ("PHU", "Phó, phụ", "副社長", "ふくしゃちょう", "Phó giám đốc"),
    "割": ("THAT", "Chia, tỉ lệ", "割引", "わりびき", "Giảm giá"),
    "劇": ("KICH", "Kịch, kịch tính", "演劇", "えんげき", "Kịch, sân khấu"),
    "力": ("LUC", "Sức mạnh, lực", "努力", "どりょく", "Nỗ lực"),
    "加": ("GIA", "Thêm, gia", "加える", "くわえる", "Thêm vào"),
    "功": ("CONG", "Công lao, thành công", "成功", "せいこう", "Thành công"),
    "助": ("TRO", "Giúp đỡ", "助ける", "たすける", "Giúp đỡ, cứu"),
    "努": ("NO", "Cố gắng", "努力", "どりょく", "Nỗ lực"),
    "労": ("LAO", "Lao động, nhọc mệt", "労働", "ろうどう", "Lao động"),
    "励": ("LE", "Khuyến khích", "励ます", "はげます", "Khích lệ"),
    "効": ("HIEU", "Hiệu quả", "効果", "こうか", "Hiệu quả"),
    "勇": ("DUNG", "Dũng cảm", "勇気", "ゆうき", "Dũng cảm"),
    "勉": ("MAN", "Cố gắng, học", "勉強", "べんきょう", "Học tập"),
    "動": ("DONG", "Chuyển động, động", "運動", "うんどう", "Vận động"),
    "務": ("VU", "Nhiệm vụ, công vụ", "業務", "ぎょうむ", "Công vụ, nghiệp vụ"),
    "勝": ("THANG", "Thắng, chiến thắng", "勝利", "しょうり", "Chiến thắng"),
    "勤": ("CAN", "Siêng năng, làm việc", "勤務", "きんむ", "Làm việc, công vụ"),
    "募": ("MO", "Tuyển, chiêu mộ", "募集", "ぼしゅう", "Tuyển dụng"),
    "勢": ("THE", "Thế lực, khí thế", "勢い", "いきおい", "Khí thế"),
    "勧": ("KHUYEN", "Khuyên, mời", "勧める", "すすめる", "Khuyên, giới thiệu"),
    "句": ("CU", "Câu, cụm từ", "俳句", "はいく", "Thơ haiku"),
    "包": ("BAO", "Bọc, gói", "包む", "つつむ", "Gói, bọc"),
    "化": ("HOA", "Hóa, biến đổi", "文化", "ぶんか", "Văn hóa"),
    "北": ("BAC", "Phía bắc", "北海道", "ほっかいどう", "Hokkaido"),
    "区": ("KHU", "Khu, quận", "地区", "ちく", "Khu vực"),
    "匹": ("THIET", "Con (đơn vị đếm thú)", "三匹", "さんびき", "Ba con (thú)"),
    "医": ("Y", "Y tế, bác sĩ", "医者", "いしゃ", "Bác sĩ"),
    "十": ("THAP", "Mười", "十月", "じゅうがつ", "Tháng mười"),
    "千": ("THIEN", "Nghìn", "千円", "せんえん", "Một nghìn yên"),
    "午": ("NGO", "Buổi trưa, ngọ", "午後", "ごご", "Buổi chiều"),
    "半": ("BAN", "Nửa", "半分", "はんぶん", "Một nửa"),
    "卒": ("TOT", "Tốt nghiệp, lính", "卒業", "そつぎょう", "Tốt nghiệp"),
    "卓": ("TRAC", "Xuất sắc, bàn", "卓球", "たっきゅう", "Bóng bàn"),
    "協": ("HIEP", "Hợp tác", "協力", "きょうりょく", "Hợp tác"),
    "南": ("NAM", "Phía nam", "南米", "なんべい", "Nam Mỹ"),
    "博": ("BAC", "Rộng, bác học", "博物館", "はくぶつかん", "Bảo tàng"),
    "占": ("CHIEM", "Chiếm, bói", "占める", "しめる", "Chiếm"),
    "印": ("AN", "Dấu ấn, in", "印鑑", "いんかん", "Con dấu"),
    "危": ("NGUY", "Nguy hiểm", "危険", "きけん", "Nguy hiểm"),
    "卵": ("LOAN", "Trứng", "卵", "たまご", "Trứng"),
    "却": ("KHACH", "Trái lại, từ chối", "退却", "たいきゃく", "Rút lui"),
    "巻": ("QUAN", "Cuộn, tập", "第一巻", "だいいっかん", "Tập một"),
    "厚": ("HAU", "Dày, hậu hĩnh", "厚い", "あつい", "Dày"),
    "原": ("NGUYEN", "Nguyên, đồng bằng", "原因", "げんいん", "Nguyên nhân"),
    "去": ("KHU", "Đi, qua", "去年", "きょねん", "Năm ngoái"),
    "参": ("TAM", "Tham gia, đến", "参加", "さんか", "Tham gia"),
    "又": ("HUU", "Lại, cũng", "又は", "または", "Hoặc là"),
    "及": ("CAP", "Và, đạt tới", "及ぶ", "およぶ", "Đạt tới, kéo dài"),
    "友": ("HUU", "Bạn bè", "友達", "ともだち", "Bạn bè"),
    "反": ("PHAN", "Phản, chống lại", "反省", "はんせい", "Phản tỉnh, suy nghĩ lại"),
    "収": ("THU", "Thu nhận, thu hoạch", "収入", "しゅうにゅう", "Thu nhập"),
    "双": ("SONG", "Đôi, cặp", "双子", "ふたご", "Sinh đôi"),
    "取": ("THU", "Lấy, nhận", "取る", "とる", "Lấy, nhận"),
    "受": ("THU", "Nhận, tiếp nhận", "受ける", "うける", "Nhận, tiếp nhận"),
    "口": ("KHAU", "Miệng, cửa", "入口", "いりぐち", "Lối vào"),
    "右": ("HUU", "Phải, bên phải", "右手", "みぎて", "Tay phải"),
    "古": ("CO", "Cũ, cổ", "古い", "ふるい", "Cũ, lâu đời"),
    "台": ("DAI", "Bệ, đài, số đếm máy móc", "台風", "たいふう", "Bão"),
    "号": ("HIEU", "Số, hiệu", "番号", "ばんごう", "Số điện thoại, số thứ tự"),
    "史": ("SU", "Lịch sử", "歴史", "れきし", "Lịch sử"),
    "司": ("TU", "Quản lý, tư", "会社", "かいしゃ", "Công ty"),
    "可": ("KHA", "Có thể, được phép", "可能", "かのう", "Có thể"),
    "召": ("TRIEU", "Triệu tập, gọi", "召す", "めす", "Gọi (kính ngữ)"),
    "叱": ("SIET", "Mắng, la mắng", "叱る", "しかる", "Mắng"),
    "名": ("DANH", "Tên, danh tiếng", "名前", "なまえ", "Tên"),
    "合": ("HOP", "Hợp, phù hợp", "合う", "あう", "Hợp, phù hợp"),
    "向": ("HUONG", "Hướng, quay về", "方向", "ほうこう", "Hướng, phương hướng"),
    "各": ("CAC", "Mỗi, các", "各自", "かくじ", "Mỗi người"),
    "吸": ("HAP", "Hít vào, hút", "吸う", "すう", "Hút, hít"),
    "叫": ("GIAO", "Kêu, hét", "叫ぶ", "さけぶ", "Hét lên"),
    "吐": ("TO", "Nôn, thổ lộ", "吐く", "はく", "Nôn mửa"),
    "君": ("QUAN", "Anh, bạn (thân mật)", "君", "きみ", "Bạn, anh (thân mật)"),
    "告": ("CAO", "Báo, thông báo", "告げる", "つげる", "Báo, thông báo"),
    "否": ("PHU", "Phủ nhận, không", "否定", "ひてい", "Phủ định"),
    "含": ("HAM", "Chứa, bao gồm", "含む", "ふくむ", "Bao gồm, chứa"),
    "吹": ("XUY", "Thổi", "吹く", "ふく", "Thổi"),
    "呂": ("LU", "Nhà tắm, âm nhạc", "風呂", "ふろ", "Bồn tắm"),
    "吠": ("PHI", "Sủa (chó)", "吠える", "ほえる", "Sủa"),
    "味": ("VI", "Mùi vị, thú vị", "意味", "いみ", "Ý nghĩa"),
    "命": ("MENH", "Mạng sống, mệnh lệnh", "命令", "めいれい", "Mệnh lệnh"),
    "和": ("HOA", "Hòa bình, Nhật", "平和", "へいわ", "Hòa bình"),
    "周": ("CHU", "Xung quanh, tuần", "周り", "まわり", "Xung quanh"),
    "呼": ("HO", "Gọi", "呼ぶ", "よぶ", "Gọi"),
    "品": ("PHAM", "Phẩm chất, sản phẩm", "作品", "さくひん", "Tác phẩm"),
    "咲": ("TUOC", "Nở (hoa)", "咲く", "さく", "Nở hoa"),
    "員": ("VIEN", "Thành viên, nhân viên", "会員", "かいいん", "Thành viên"),
    "商": ("THUONG", "Buôn bán, thương mại", "商売", "しょうばい", "Buôn bán"),
    "問": ("VAN", "Hỏi, vấn đề", "問題", "もんだい", "Vấn đề"),
    "喜": ("HY", "Vui mừng", "喜ぶ", "よろこぶ", "Vui mừng"),
    "善": ("THIEN", "Tốt lành, thiện", "善意", "ぜんい", "Thiện ý"),
    "喫": ("KHIET", "Uống, ăn", "喫茶店", "きっさてん", "Tiệm cà phê"),
    "器": ("KHI", "Dụng cụ, khí", "楽器", "がっき", "Nhạc cụ"),
    "四": ("TU", "Bốn", "四月", "しがつ", "Tháng tư"),
    "回": ("HOI", "Vòng, lần", "回る", "まわる", "Quay vòng"),
    "因": ("NHAN", "Nguyên nhân", "原因", "げんいん", "Nguyên nhân"),
    "団": ("DOAN", "Đoàn, nhóm", "団体", "だんたい", "Đoàn thể"),
    "図": ("DO", "Bản đồ, hình vẽ", "地図", "ちず", "Bản đồ"),
    "囲": ("VI", "Bao vây, xung quanh", "囲む", "かこむ", "Bao quanh"),
    "困": ("KON", "Khó khăn, bối rối", "困る", "こまる", "Khó khăn, bối rối"),
    "国": ("QUOC", "Quốc gia, đất nước", "外国", "がいこく", "Nước ngoài"),
    "固": ("CO", "Cứng, kiên cố", "固い", "かたい", "Cứng"),
    "園": ("VIEN", "Vườn, khu", "公園", "こうえん", "Công viên"),
    "土": ("THO", "Đất", "土地", "とち", "Đất đai"),
    "圧": ("AP", "Áp lực, ép", "圧力", "あつりょく", "Áp lực"),
    "地": ("DIA", "Đất, địa", "地球", "ちきゅう", "Trái đất"),
    "在": ("TAI", "Tồn tại, ở", "存在", "そんざい", "Sự tồn tại"),
    "坂": ("BAN", "Dốc, sườn dốc", "坂道", "さかみち", "Đường dốc"),
    "均": ("QUAN", "Đều, bình quân", "平均", "へいきん", "Bình quân"),
    "坊": ("PHONG", "Chú bé, khu phố", "赤ん坊", "あかんぼう", "Em bé sơ sinh"),
    "型": ("HINH", "Kiểu, mẫu", "型", "かた", "Kiểu dáng, mẫu"),
    "城": ("THANH", "Lâu đài, thành", "城", "しろ", "Lâu đài"),
    "堂": ("DUONG", "Sảnh, nhà thờ", "食堂", "しょくどう", "Nhà ăn"),
    "基": ("CO", "Cơ sở, nền tảng", "基本", "きほん", "Cơ bản"),
    "域": ("VUC", "Khu vực, vùng", "地域", "ちいき", "Khu vực"),
    "場": ("TRUONG", "Nơi chốn, sân", "場所", "ばしょ", "Nơi chốn"),
    "報": ("BAO", "Báo cáo, thông tin", "情報", "じょうほう", "Thông tin"),
    "塩": ("YEM", "Muối", "塩", "しお", "Muối"),
    "墓": ("MO", "Mộ, phần mộ", "墓地", "ぼち", "Nghĩa địa"),
    "塗": ("DO", "Sơn, phết", "塗る", "ぬる", "Sơn, bôi"),
    "境": ("CANH", "Biên giới, hoàn cảnh", "環境", "かんきょう", "Môi trường"),
    "増": ("TANG", "Tăng thêm", "増える", "ふえる", "Tăng lên"),
    "塾": ("THUC", "Trường luyện thi", "塾", "じゅく", "Trường luyện thi"),
    "壊": ("HOAI", "Vỡ, hỏng", "壊れる", "こわれる", "Hỏng, vỡ"),
    "壁": ("BICH", "Tường, vách", "壁", "かべ", "Bức tường"),
    "士": ("SI", "Sĩ, chiến sĩ", "武士", "ぶし", "Võ sĩ"),
    "声": ("THANH", "Giọng nói, tiếng", "声", "こえ", "Giọng nói"),
    "売": ("MAI", "Bán", "売る", "うる", "Bán"),
    "変": ("BIEN", "Thay đổi, biến", "変化", "へんか", "Thay đổi"),
    "夏": ("HA", "Mùa hè", "夏休み", "なつやすみ", "Nghỉ hè"),
    "夕": ("TICH", "Buổi tối, chiều", "夕食", "ゆうしょく", "Bữa tối"),
    "外": ("NGOAI", "Ngoài, bên ngoài", "外国", "がいこく", "Nước ngoài"),
    "多": ("DA", "Nhiều", "多い", "おおい", "Nhiều"),
    "夜": ("DA", "Đêm", "夜中", "よなか", "Giữa đêm"),
    "夢": ("MONG", "Giấc mơ", "夢中", "むちゅう", "Mê say, chìm đắm"),
    "天": ("THIEN", "Trời, thiên", "天気", "てんき", "Thời tiết"),
    "太": ("THAI", "Béo, to", "太い", "ふとい", "Béo, to"),
    "夫": ("PHU", "Chồng, đàn ông", "夫婦", "ふうふ", "Vợ chồng"),
    "央": ("UONG", "Trung tâm, giữa", "中央", "ちゅうおう", "Trung tâm"),
    "失": ("THAT", "Mất, thất bại", "失敗", "しっぱい", "Thất bại"),
    "奇": ("KY", "Kỳ lạ, lẻ", "奇妙", "きみょう", "Kỳ lạ"),
    "奏": ("TAU", "Tấu nhạc", "演奏", "えんそう", "Biểu diễn âm nhạc"),
    "契": ("KHE", "Khế ước, hợp đồng", "契約", "けいやく", "Hợp đồng"),
    "奥": ("AOA", "Trong sâu, bên trong", "奥さん", "おくさん", "Vợ (lịch sự)"),
    "奨": ("KHUYEN", "Khuyến khích, thưởng", "奨学金", "しょうがくきん", "Học bổng"),
    "女": ("NU", "Nữ, phụ nữ", "女性", "じょせい", "Phụ nữ"),
    "好": ("HAO", "Thích, tốt", "好き", "すき", "Thích"),
    "妙": ("DIEU", "Kỳ diệu, hay", "妙な", "みょうな", "Kỳ lạ"),
    "姉": ("TY", "Chị gái", "姉", "あね", "Chị gái"),
    "妹": ("MAI", "Em gái", "妹", "いもうと", "Em gái"),
    "始": ("THY", "Bắt đầu", "始まる", "はじまる", "Bắt đầu"),
    "妻": ("THE", "Vợ", "妻", "つま", "Vợ"),
    "姿": ("TU", "Dáng vẻ, hình dạng", "姿勢", "しせい", "Tư thế"),
    "娘": ("NUONG", "Con gái", "娘", "むすめ", "Con gái"),
    "姫": ("HY", "Công chúa, tiểu thư", "姫", "ひめ", "Công chúa"),
    "婦": ("PHU", "Phụ nữ, vợ", "主婦", "しゅふ", "Nội trợ"),
    "婚": ("HON", "Hôn nhân", "結婚", "けっこん", "Kết hôn"),
    "嫌": ("KIEN", "Ghét, khó chịu", "嫌い", "きらい", "Ghét"),
    "嬉": ("HY", "Vui mừng", "嬉しい", "うれしい", "Vui mừng"),
    "嬢": ("NUONG", "Tiểu thư, cô gái", "令嬢", "れいじょう", "Tiểu thư"),
    "子": ("TU", "Con, trẻ em", "子供", "こども", "Trẻ em"),
    "字": ("TU", "Chữ, ký tự", "文字", "もじ", "Chữ viết"),
    "存": ("TON", "Tồn tại", "存在", "そんざい", "Sự tồn tại"),
    "学": ("HOC", "Học, học vấn", "学校", "がっこう", "Trường học"),
    "季": ("QUY", "Mùa", "季節", "きせつ", "Mùa, tiết"),
    "孫": ("TON", "Cháu", "孫", "まご", "Cháu"),
    "安": ("AN", "Yên bình, rẻ", "安全", "あんぜん", "An toàn"),
    "守": ("THU", "Bảo vệ, giữ", "守る", "まもる", "Bảo vệ"),
    "宇": ("VU", "Vũ trụ", "宇宙", "うちゅう", "Vũ trụ"),
    "宅": ("TRACH", "Nhà ở", "自宅", "じたく", "Nhà riêng"),
    "完": ("HOAN", "Hoàn toàn, xong", "完成", "かんせい", "Hoàn thành"),
    "実": ("THUC", "Thực tế, quả", "実際", "じっさい", "Thực tế"),
    "定": ("DINH", "Định, xác định", "決定", "けってい", "Quyết định"),
    "官": ("QUAN", "Quan chức, công chức", "官僚", "かんりょう", "Quan liêu"),
    "宗": ("TONG", "Tôn giáo, tông", "宗教", "しゅうきょう", "Tôn giáo"),
    "宙": ("TRU", "Không trung, vũ trụ", "宇宙", "うちゅう", "Vũ trụ"),
    "宝": ("BAO", "Kho báu, quý báu", "宝物", "たからもの", "Của báu"),
    "室": ("THUAT", "Phòng", "教室", "きょうしつ", "Lớp học"),
    "客": ("KHACH", "Khách", "お客さん", "おきゃくさん", "Khách hàng"),
    "家": ("GIA", "Nhà, gia đình", "家族", "かぞく", "Gia đình"),
    "宮": ("CUNG", "Cung điện, đền", "宮殿", "きゅうでん", "Cung điện"),
    "害": ("HAI", "Hại, thiệt hại", "被害", "ひがい", "Thiệt hại"),
    "容": ("DUNG", "Dung mạo, chứa", "容量", "ようりょう", "Dung lượng"),
    "宴": ("YEN", "Tiệc, yến", "宴会", "えんかい", "Tiệc tùng"),
    "宿": ("TUC", "Nhà trọ, nghỉ lại", "宿泊", "しゅくはく", "Lưu trú"),
    "寄": ("KY", "Gần, gửi", "寄付", "きふ", "Quyên góp, đóng góp"),
    "密": ("MAT", "Mật, bí mật", "秘密", "ひみつ", "Bí mật"),
    "寂": ("TICH", "Tĩnh lặng, cô đơn", "寂しい", "さびしい", "Cô đơn"),
    "寒": ("HAN", "Lạnh", "寒い", "さむい", "Lạnh"),
    "富": ("PHU", "Giàu có, phong phú", "富士山", "ふじさん", "Núi Phú Sĩ"),
    "寝": ("TIM", "Ngủ, nằm", "寝る", "ねる", "Đi ngủ"),
    "察": ("SAT", "Quan sát, suy đoán", "観察", "かんさつ", "Quan sát"),
    "寮": ("LIEU", "Ký túc xá, khu ở", "寮", "りょう", "Ký túc xá"),
    "寸": ("THON", "Tấc (đơn vị đo)", "寸法", "すんぽう", "Kích thước"),
    "寺": ("TU", "Chùa, đền", "寺", "てら", "Chùa"),
    "対": ("DOI", "Đối, so sánh", "対する", "たいする", "Đối với"),
    "寿": ("THO", "Thọ, tuổi thọ", "長寿", "ちょうじゅ", "Trường thọ"),
    "専": ("CHUYEN", "Chuyên môn", "専門", "せんもん", "Chuyên môn"),
    "封": ("PHONG", "Phong bì, đóng gói", "封筒", "ふうとう", "Phong bì"),
    "射": ("XA", "Bắn, phóng", "射る", "いる", "Bắn"),
    "将": ("TUONG", "Tướng, sắp", "将来", "しょうらい", "Tương lai"),
    "尊": ("TON", "Tôn trọng", "尊敬", "そんけい", "Tôn kính"),
    "尋": ("TAM", "Tìm kiếm", "尋ねる", "たずねる", "Hỏi, tìm kiếm"),
    "導": ("DAO", "Hướng dẫn, dẫn đầu", "指導", "しどう", "Hướng dẫn"),
    "小": ("TIEU", "Nhỏ", "小学校", "しょうがっこう", "Trường tiểu học"),
    "少": ("THIEU", "Ít, thiếu", "少し", "すこし", "Một chút"),
    "当": ("DUONG", "Đúng, trúng, đương", "当然", "とうぜん", "Đương nhiên"),
    "就": ("THU", "Nhận việc, theo", "就職", "しゅうしょく", "Tìm việc làm"),
    "局": ("CUC", "Cục, phòng ban", "郵便局", "ゆうびんきょく", "Bưu điện"),
    "居": ("CU", "Ở, ngồi", "居間", "いま", "Phòng khách"),
    "届": ("DICH", "Giao đến, đạt tới", "届く", "とどく", "Đến nơi, nhận được"),
    "屋": ("OC", "Mái nhà, cửa hàng", "屋根", "やね", "Mái nhà"),
    "展": ("TRIEN", "Mở rộng, triển lãm", "展覧会", "てんらんかい", "Triển lãm"),
    "層": ("TANG", "Tầng, lớp", "階層", "かいそう", "Tầng lớp"),
    "履": ("LY", "Giày dép, thực hiện", "履く", "はく", "Mang (giày)"),
    "山": ("SON", "Núi", "山登り", "やまのぼり", "Leo núi"),
    "岩": ("NHAM", "Đá, tảng đá", "岩", "いわ", "Tảng đá"),
    "岸": ("NGAN", "Bờ sông, bờ biển", "海岸", "かいがん", "Bờ biển"),
    "島": ("DAO", "Đảo", "島", "しま", "Đảo"),
    "崩": ("BUNG", "Sụp đổ", "崩れる", "くずれる", "Sụp đổ, tan vỡ"),
    "川": ("XUYEN", "Sông, suối", "川", "かわ", "Con sông"),
    "州": ("CHAU", "Châu, tiểu bang", "本州", "ほんしゅう", "Honshu"),
    "工": ("CONG", "Công nhân, sản xuất", "工場", "こうじょう", "Nhà máy"),
    "左": ("TA", "Trái, bên trái", "左手", "ひだりて", "Tay trái"),
    "差": ("SAI", "Sự khác biệt, sai số", "差別", "さべつ", "Phân biệt"),
    "己": ("KY", "Bản thân", "自己", "じこ", "Bản thân"),
    "市": ("THI", "Thành phố, chợ", "市場", "いちば", "Chợ"),
    "布": ("BO", "Vải, rải ra", "布団", "ふとん", "Chăn, đệm"),
    "希": ("HY", "Hi vọng, hiếm", "希望", "きぼう", "Hi vọng"),
    "帰": ("QUY", "Về, trở về", "帰る", "かえる", "Về nhà"),
    "席": ("TICH", "Chỗ ngồi", "席", "せき", "Chỗ ngồi"),
    "帯": ("DAI", "Đai, vùng", "熱帯", "ねったい", "Nhiệt đới"),
    "師": ("SU", "Thầy, sư", "教師", "きょうし", "Giáo viên"),
    "帳": ("TRUONG", "Sổ, màn", "手帳", "てちょう", "Sổ tay"),
    "常": ("THUONG", "Thường, bình thường", "日常", "にちじょう", "Hàng ngày"),
    "帽": ("MAO", "Mũ", "帽子", "ぼうし", "Mũ"),
    "干": ("CAN", "Khô, can thiệp", "干渉", "かんしょう", "Can thiệp"),
    "平": ("BINH", "Bằng phẳng, hòa bình", "平和", "へいわ", "Hòa bình"),
    "年": ("NIEN", "Năm", "来年", "らいねん", "Năm sau"),
    "幸": ("HANH", "Hạnh phúc", "幸せ", "しあわせ", "Hạnh phúc"),
    "幹": ("CAN", "Thân cây, cốt lõi", "幹部", "かんぶ", "Lãnh đạo, cốt cán"),
    "幼": ("AU", "Ấu thơ, nhỏ bé", "幼稚園", "ようちえん", "Mẫu giáo"),
    "広": ("QUANG", "Rộng", "広い", "ひろい", "Rộng"),
    "床": ("THUONG", "Sàn nhà, giường", "床", "ゆか", "Sàn nhà"),
    "店": ("DIEM", "Cửa hàng", "店員", "てんいん", "Nhân viên cửa hàng"),
    "府": ("PHU", "Phủ, chính quyền", "政府", "せいふ", "Chính phủ"),
    "度": ("DO", "Độ, lần", "今度", "こんど", "Lần này, lần tới"),
    "庫": ("KHO", "Kho", "倉庫", "そうこ", "Kho bãi"),
    "庭": ("DINH", "Sân, vườn", "庭園", "ていえん", "Vườn hoa"),
    "座": ("TOA", "Ngồi, ghế", "座る", "すわる", "Ngồi"),
    "康": ("KHANG", "Khỏe mạnh", "健康", "けんこう", "Sức khỏe"),
    "廊": ("LANG", "Hành lang", "廊下", "ろうか", "Hành lang"),
    "建": ("KIEN", "Xây dựng", "建物", "たてもの", "Tòa nhà"),
    "井": ("THINGH", "Giếng", "井戸", "いど", "Giếng nước"),
    "弁": ("BIEN", "Biện hộ, bàn luận", "弁当", "べんとう", "Hộp cơm"),
    "式": ("THUC", "Nghi lễ, công thức", "式", "しき", "Nghi lễ"),
    "弓": ("CUNG", "Cung tên", "弓道", "きゅうどう", "Cung đạo"),
    "引": ("DAN", "Kéo, dẫn", "引く", "ひく", "Kéo"),
    "弟": ("DE", "Em trai", "弟", "おとうと", "Em trai"),
    "弱": ("NUOC", "Yếu", "弱い", "よわい", "Yếu"),
    "強": ("CUONG", "Mạnh, cứng", "強い", "つよい", "Mạnh"),
    "張": ("TRUONG", "Căng, mở rộng", "緊張", "きんちょう", "Hồi hộp, căng thẳng"),
    "弾": ("DAN", "Đạn, đàn", "爆弾", "ばくだん", "Bom"),
    "彙": ("HUY", "Từ vựng, tập hợp", "語彙", "ごい", "Từ vựng"),
    "形": ("HINH", "Hình dạng", "形", "かたち", "Hình dạng"),
    "影": ("ANH", "Bóng, ảnh", "影響", "えいきょう", "Ảnh hưởng"),
    "役": ("DICH", "Vai trò, nghĩa vụ", "役立つ", "やくだつ", "Hữu ích"),
    "往": ("VANG", "Đi, qua lại", "往来", "おうらい", "Qua lại"),
    "彼": ("BI", "Anh ấy", "彼女", "かのじょ", "Cô ấy, bạn gái"),
    "後": ("HAU", "Sau, phía sau", "以後", "いご", "Từ đây về sau"),
    "待": ("DAI", "Chờ đợi", "待つ", "まつ", "Chờ đợi"),
    "律": ("LUAT", "Luật lệ", "規律", "きりつ", "Kỷ luật"),
    "徒": ("DO", "Đi bộ, học trò", "生徒", "せいと", "Học sinh"),
    "従": ("TUNG", "Theo, tòng", "従う", "したがう", "Tuân theo"),
    "得": ("DAC", "Được, đạt được", "得る", "える", "Đạt được"),
    "復": ("PHUC", "Phục hồi, trở lại", "回復", "かいふく", "Hồi phục"),
    "御": ("NGU", "Kính, ngự", "御飯", "ごはん", "Cơm"),
    "徴": ("TRUNG", "Trưng thu, đặc trưng", "特徴", "とくちょう", "Đặc điểm"),
    "単": ("DON", "Đơn, đơn giản", "単語", "たんご", "Từ vựng"),
    "営": ("KINH", "Kinh doanh", "営業", "えいぎょう", "Kinh doanh"),
    "厳": ("NGHIEM", "Nghiêm khắc", "厳しい", "きびしい", "Nghiêm khắc"),
    "心": ("TAM", "Tâm, tim", "心配", "しんぱい", "Lo lắng"),
    "必": ("TAT", "Nhất định, tất yếu", "必要", "ひつよう", "Cần thiết"),
    "応": ("UNG", "Ứng phó, trả lời", "対応", "たいおう", "Đối phó"),
    "志": ("CHI", "Chí hướng, ý chí", "意志", "いし", "Ý chí"),
    "忘": ("VONG", "Quên", "忘れる", "わすれる", "Quên"),
    "忍": ("NHON", "Nhẫn, chịu đựng", "忍耐", "にんたい", "Nhẫn nại"),
    "念": ("NIEM", "Niệm, nghĩ", "記念", "きねん", "Kỷ niệm"),
    "急": ("CAP", "Gấp, cấp bách", "急ぐ", "いそぐ", "Vội vàng"),
    "怒": ("NO", "Tức giận", "怒る", "おこる", "Tức giận"),
    "怠": ("DAI", "Lười biếng, trây lười", "怠る", "おこたる", "Lười biếng"),
    "思": ("TU", "Suy nghĩ", "思う", "おもう", "Suy nghĩ, cảm thấy"),
    "息": ("TUC", "Hơi thở, con", "息子", "むすこ", "Con trai"),
    "恐": ("KHUNG", "Sợ hãi", "恐れ", "おそれ", "Nỗi sợ"),
    "恥": ("LIEM", "Xấu hổ", "恥ずかしい", "はずかしい", "Xấu hổ"),
    "恋": ("LIEN", "Tình yêu", "恋愛", "れんあい", "Tình yêu"),
    "悪": ("AC", "Xấu, ác", "悪い", "わるい", "Xấu"),
    "患": ("HOAN", "Bệnh nhân, lo âu", "患者", "かんじゃ", "Bệnh nhân"),
    "悲": ("BI", "Buồn bã", "悲しい", "かなしい", "Buồn"),
    "惑": ("HOAC", "Mê hoặc, bối rối", "困惑", "こんわく", "Bối rối"),
    "意": ("Y", "Ý, ý nghĩa", "意味", "いみ", "Ý nghĩa"),
    "感": ("CAM", "Cảm xúc", "感謝", "かんしゃ", "Biết ơn"),
    "想": ("TUONG", "Suy nghĩ, ý tưởng", "思想", "しそう", "Tư tưởng"),
    "愛": ("AI", "Yêu, tình yêu", "愛情", "あいじょう", "Tình yêu"),
    "態": ("THAI", "Thái độ, trạng thái", "態度", "たいど", "Thái độ"),
    "慕": ("MO", "Nhớ, ngưỡng mộ", "慕う", "したう", "Ngưỡng mộ"),
    "慮": ("LU", "Suy nghĩ, lo ngại", "考慮", "こうりょ", "Cân nhắc, xem xét"),
    "憩": ("NGHI", "Nghỉ ngơi", "休憩", "きゅうけい", "Nghỉ giải lao"),
    "懸": ("HIEN", "Treo, lo lắng", "懸命", "けんめい", "Nỗ lực hết mình"),
    "忙": ("MANG", "Bận rộn", "忙しい", "いそがしい", "Bận rộn"),
    "快": ("KHOI", "Dễ chịu, sảng khoái", "快適", "かいてき", "Thoải mái"),
    "性": ("TINH", "Tính cách, giới tính", "性格", "せいかく", "Tính cách"),
    "怖": ("PHA", "Sợ hãi", "怖い", "こわい", "Đáng sợ"),
    "怪": ("QUAI", "Kỳ lạ, yêu quái", "怪しい", "あやしい", "Kỳ lạ, đáng ngờ"),
    "悔": ("HOI", "Hối hận", "後悔", "こうかい", "Hối hận"),
    "悩": ("NAO", "Lo lắng, phiền muộn", "悩む", "なやむ", "Lo lắng, băn khoăn"),
    "情": ("TINH", "Tình cảm, thông tin", "感情", "かんじょう", "Cảm xúc"),
    "惜": ("TIEC", "Tiếc", "惜しい", "おしい", "Đáng tiếc"),
    "慌": ("HOANG", "Hoảng loạn, vội vã", "慌てる", "あわてる", "Hoảng loạn"),
    "愉": ("DU", "Vui vẻ", "愉快", "ゆかい", "Vui vẻ, sảng khoái"),
    "慎": ("THAN", "Cẩn thận, thận trọng", "慎重", "しんちょう", "Thận trọng"),
    "慣": ("QUAN", "Quen, thói quen", "習慣", "しゅうかん", "Thói quen"),
    "慢": ("MAN", "Chậm, kiêu ngạo", "自慢", "じまん", "Tự hào, khoe khoang"),
    "憎": ("TANG", "Ghét, căm thù", "憎む", "にくむ", "Ghét, căm thù"),
    "憶": ("UC", "Nhớ, ký ức", "記憶", "きおく", "Ký ức"),
    "懐": ("HOAI", "Hoài niệm, lòng", "懐かしい", "なつかしい", "Hoài niệm"),
    "成": ("THANH", "Thành công, đạt được", "成功", "せいこう", "Thành công"),
    "我": ("NGA", "Ta, bản thân", "自我", "じが", "Bản ngã"),
    "戚": ("THICH", "Họ hàng, buồn bã", "親戚", "しんせき", "Họ hàng"),
    "戦": ("CHIEN", "Chiến đấu", "戦争", "せんそう", "Chiến tranh"),
    "房": ("PHONG", "Buồng, phòng", "台所", "だいどころ", "Nhà bếp"),
    "所": ("SO", "Nơi chốn", "場所", "ばしょ", "Nơi chốn"),
    "才": ("TAI", "Tài năng, tuổi", "天才", "てんさい", "Thiên tài"),
    "手": ("THU", "Tay", "手紙", "てがみ", "Thư"),
    "打": ("TA", "Đánh, đập", "打つ", "うつ", "Đánh"),
    "私": ("TU", "Tôi, tư nhân", "私立", "しりつ", "Tư lập"),
    "投": ("DAU", "Ném, đầu tư", "投資", "とうし", "Đầu tư"),
    "折": ("CHAT", "Gấp, bẻ", "折れる", "おれる", "Gãy, bẻ gãy"),
    "技": ("KY", "Kỹ thuật", "技術", "ぎじゅつ", "Kỹ thuật"),
    "招": ("TRIEU", "Mời, chiêu", "招待", "しょうたい", "Mời"),
    "担": ("DAM", "Đảm nhận, gánh", "担当", "たんとう", "Phụ trách"),
    "拝": ("BAI", "Bái, lạy", "拝む", "おがむ", "Lạy, cầu nguyện"),
    "押": ("AP", "Đẩy, ấn", "押す", "おす", "Đẩy, ấn"),
    "抱": ("BAO", "Ôm, bế", "抱く", "だく", "Ôm"),
    "指": ("CHI", "Ngón tay, chỉ", "指す", "さす", "Chỉ vào"),
    "持": ("TRI", "Giữ, cầm", "持つ", "もつ", "Giữ, cầm"),
    "拾": ("THAP", "Nhặt, lượm", "拾う", "ひろう", "Nhặt lên"),
    "振": ("CHAN", "Vẫy, rung", "振る", "ふる", "Vẫy, lắc"),
    "挫": ("TOA", "Gãy, thất bại", "挫折", "ざせつ", "Thất bại, vấp ngã"),
    "採": ("TUYEN", "Thu thập, tuyển", "採用", "さいよう", "Tuyển dụng"),
    "授": ("THU", "Dạy, trao", "授業", "じゅぎょう", "Bài giảng, tiết học"),
    "接": ("TIEP", "Tiếp xúc, kết nối", "接続", "せつぞく", "Kết nối"),
    "捨": ("XA", "Bỏ, vứt", "捨てる", "すてる", "Vứt bỏ"),
    "探": ("THAM", "Tìm kiếm, thám", "探す", "さがす", "Tìm kiếm"),
    "描": ("MIEU", "Vẽ, miêu tả", "描く", "かく", "Vẽ"),
    "掛": ("QUA", "Treo, mắc", "掛ける", "かける", "Treo, mắc"),
    "掃": ("QUET", "Quét dọn", "掃除", "そうじ", "Dọn dẹp"),
    "握": ("AC", "Nắm chặt", "握手", "あくしゅ", "Bắt tay"),
    "援": ("VIEN", "Viện trợ, giúp đỡ", "支援", "しえん", "Hỗ trợ"),
    "換": ("HOAN", "Đổi, chuyển đổi", "交換", "こうかん", "Trao đổi"),
    "揚": ("DUONG", "Nâng lên, chiên", "揚げる", "あげる", "Chiên rán"),
    "揺": ("DIEU", "Lắc, rung", "揺れる", "ゆれる", "Rung lắc"),
    "損": ("TON", "Tổn thất, hỏng", "損害", "そんがい", "Thiệt hại"),
    "携": ("THE", "Mang theo, đưa tay", "携帯", "けいたい", "Điện thoại di động"),
    "操": ("THAO", "Thao tác, vận hành", "操作", "そうさ", "Thao tác"),
    "挙": ("CU", "Giơ tay, bầu cử", "挙げる", "あげる", "Giơ lên"),
    "支": ("CHI", "Hỗ trợ, chi nhánh", "支店", "してん", "Chi nhánh"),
    "改": ("CAI", "Cải thiện, sửa đổi", "改善", "かいぜん", "Cải thiện"),
    "攻": ("CONG", "Tấn công", "攻撃", "こうげき", "Tấn công"),
    "放": ("PHONG", "Phóng, thả", "放送", "ほうそう", "Phát sóng"),
    "故": ("CO", "Cố ý, cũ", "故郷", "こきょう", "Quê hương"),
    "政": ("CHINH", "Chính trị", "政治", "せいじ", "Chính trị"),
    "教": ("GIAO", "Dạy, tôn giáo", "教育", "きょういく", "Giáo dục"),
    "救": ("CUU", "Cứu giúp", "救急", "きゅうきゅう", "Cấp cứu"),
    "敗": ("BAI", "Thất bại", "失敗", "しっぱい", "Thất bại"),
    "散": ("TAN", "Tản, phân tán", "散歩", "さんぽ", "Dạo bộ"),
    "敬": ("KINH", "Kính trọng", "敬語", "けいご", "Kính ngữ"),
    "数": ("SO", "Số, đếm", "数学", "すうがく", "Toán học"),
    "整": ("CHANH", "Chỉnh lý, sắp xếp", "整理", "せいり", "Sắp xếp"),
    "文": ("VAN", "Văn, chữ", "文化", "ぶんか", "Văn hóa"),
    "料": ("LIEU", "Nguyên liệu, phí", "料理", "りょうり", "Nấu ăn"),
    "断": ("DOAN", "Từ chối, đứt", "断る", "ことわる", "Từ chối"),
    "新": ("TAN", "Mới", "新しい", "あたらしい", "Mới"),
    "方": ("PHUONG", "Phương hướng, cách", "方法", "ほうほう", "Phương pháp"),
    "旅": ("LU", "Du lịch, lữ hành", "旅行", "りょこう", "Du lịch"),
    "族": ("TOC", "Tộc, gia tộc", "家族", "かぞく", "Gia đình"),
    "日": ("NHAT", "Ngày, mặt trời", "日本", "にほん", "Nhật Bản"),
    "旦": ("DAN", "Buổi sáng, đầu ngày", "元旦", "がんたん", "Ngày đầu năm"),
    "早": ("TAO", "Sớm, nhanh", "早い", "はやい", "Sớm, nhanh"),
    "旬": ("XUAN", "Thập nhật, đúng mùa", "旬", "しゅん", "Đúng mùa"),
    "明": ("MINH", "Sáng, rõ ràng", "明日", "あした", "Ngày mai"),
    "昔": ("TICH", "Xưa, ngày xưa", "昔話", "むかしばなし", "Chuyện ngày xưa"),
    "易": ("DICH", "Dễ, giao dịch", "貿易", "ぼうえき", "Thương mại"),
    "昇": ("THANG", "Lên, nâng cao", "昇進", "しょうしん", "Thăng chức"),
    "春": ("XUAN", "Mùa xuân", "春休み", "はるやすみ", "Nghỉ xuân"),
    "星": ("TINH", "Ngôi sao", "星", "ほし", "Ngôi sao"),
    "昼": ("TRUU", "Ban ngày, trưa", "昼食", "ちゅうしょく", "Bữa trưa"),
    "昨": ("TAC", "Hôm qua, năm ngoái", "昨日", "きのう", "Hôm qua"),
    "映": ("ANH", "Chiếu, phản chiếu", "映画", "えいが", "Phim"),
    "時": ("THI", "Thời gian, giờ", "時間", "じかん", "Thời gian"),
    "晴": ("TINH", "Trời nắng", "晴れ", "はれ", "Trời nắng"),
    "暑": ("THU", "Nóng (thời tiết)", "暑い", "あつい", "Nóng"),
    "景": ("CANH", "Cảnh, phong cảnh", "景色", "けしき", "Phong cảnh"),
    "晩": ("MAN", "Tối, buổi tối", "今晩", "こんばん", "Tối nay"),
    "普": ("PHO", "Phổ thông, thường", "普通", "ふつう", "Thông thường"),
    "暗": ("AM", "Tối, tối tăm", "暗い", "くらい", "Tối"),
    "暖": ("NHIEM", "Ấm áp", "暖かい", "あたたかい", "Ấm áp"),
    "暇": ("HA", "Rảnh rỗi", "暇", "ひま", "Rảnh rỗi"),
    "暮": ("MO", "Cuối năm, hoàng hôn", "暮らす", "くらす", "Sống, sinh sống"),
    "曇": ("AM", "Trời nhiều mây", "曇り", "くもり", "Trời nhiều mây"),
    "曜": ("TUOC", "Ngày trong tuần", "日曜日", "にちようび", "Chủ nhật"),
    "曰": ("VIET", "Nói rằng", "曰く", "いわく", "Nói rằng"),
    "曲": ("KHUC", "Bài nhạc, cong", "曲がる", "まがる", "Cong, rẽ"),
    "更": ("CANH", "Thêm nữa, thay đổi", "更に", "さらに", "Hơn nữa"),
    "書": ("THU", "Viết, sách", "書く", "かく", "Viết"),
    "最": ("TOI", "Tối, nhất", "最高", "さいこう", "Cao nhất"),
    "替": ("THE", "Thay thế, đổi", "替える", "かえる", "Thay đổi"),
    "月": ("NGUYET", "Trăng, tháng", "月曜日", "げつようび", "Thứ Hai"),
    "有": ("HUU", "Có, tồn tại", "有名", "ゆうめい", "Nổi tiếng"),
    "服": ("PHUC", "Quần áo, tuân theo", "服装", "ふくそう", "Trang phục"),
    "望": ("VONG", "Ước vọng, nhìn xa", "希望", "きぼう", "Hi vọng"),
    "朝": ("TRIEU", "Buổi sáng, triều đại", "朝食", "ちょうしょく", "Bữa sáng"),
    "期": ("KY", "Kỳ, giai đoạn", "学期", "がっき", "Học kỳ"),
    "木": ("MOC", "Gỗ, cây", "木曜日", "もくようび", "Thứ Năm"),
    "本": ("HON", "Gốc, sách", "本当", "ほんとう", "Thật sự"),
    "札": ("THUA", "Tờ giấy, tấm biển", "名札", "なふだ", "Thẻ tên"),
    "末": ("MAT", "Cuối, tận cùng", "週末", "しゅうまつ", "Cuối tuần"),
    "未": ("VI", "Chưa, vị", "未来", "みらい", "Tương lai"),
    "机": ("KY", "Bàn học", "机", "つくえ", "Bàn học"),
    "村": ("THON", "Làng xã", "村", "むら", "Làng"),
    "来": ("LAI", "Đến, lai", "来年", "らいねん", "Năm sau"),
    "材": ("VAT", "Vật liệu, nhân tài", "材料", "ざいりょう", "Nguyên liệu"),
    "束": ("THUC", "Bó, ràng buộc", "約束", "やくそく", "Lời hứa, hẹn"),
    "条": ("DIEU", "Điều, khoản", "条件", "じょうけん", "Điều kiện"),
    "林": ("LAM", "Rừng nhỏ", "森林", "しんりん", "Rừng"),
    "東": ("DONG", "Đông, phía đông", "東京", "とうきょう", "Tokyo"),
    "板": ("BAN", "Ván, bảng", "黒板", "こくばん", "Bảng đen"),
    "果": ("QUA", "Quả, kết quả", "結果", "けっか", "Kết quả"),
    "枝": ("CHI", "Cành cây", "枝", "えだ", "Cành cây"),
    "枚": ("MAI", "Tờ (đơn vị đếm giấy)", "一枚", "いちまい", "Một tờ"),
    "杯": ("BAI", "Ly, chén", "一杯", "いっぱい", "Một ly, đầy"),
    "柱": ("TRU", "Cột, trụ", "柱", "はしら", "Cột"),
    "栄": ("VINH", "Vinh quang, phát triển", "繁栄", "はんえい", "Thịnh vượng"),
    "査": ("TRA", "Điều tra, tra xét", "調査", "ちょうさ", "Điều tra"),
    "染": ("NHIEM", "Nhuộm, lây nhiễm", "感染", "かんせん", "Lây nhiễm"),
    "枯": ("CO", "Khô héo", "枯れる", "かれる", "Khô héo"),
    "柔": ("NHIEU", "Mềm mại, nhu", "柔らかい", "やわらかい", "Mềm mại"),
    "柄": ("BING", "Cán cầm, tính cách", "人柄", "ひとがら", "Tính cách"),
    "校": ("GIAO", "Trường học", "学校", "がっこう", "Trường học"),
    "根": ("CAN", "Rễ, căn bản", "根拠", "こんきょ", "Căn cứ, cơ sở"),
    "案": ("AN", "Kế hoạch, ý kiến", "提案", "ていあん", "Đề xuất"),
    "桜": ("ANH", "Hoa anh đào", "桜", "さくら", "Hoa anh đào"),
    "格": ("CACH", "Cách, quy cách", "価格", "かかく", "Giá cả"),
    "株": ("CHU", "Cổ phần, gốc cây", "株式", "かぶしき", "Cổ phiếu"),
    "桃": ("DAO", "Quả đào", "桃", "もも", "Quả đào"),
    "栽": ("TUYEN", "Trồng cây", "盆栽", "ぼんさい", "Bonsai"),
    "械": ("GIOI", "Máy móc", "機械", "きかい", "Máy móc"),
    "森": ("LAM", "Rừng", "森", "もり", "Rừng"),
    "植": ("THUC", "Trồng, thực vật", "植物", "しょくぶつ", "Thực vật"),
    "検": ("KIEM", "Kiểm tra", "検査", "けんさ", "Kiểm tra"),
    "棒": ("BANG", "Gậy, que", "棒", "ぼう", "Cây gậy"),
    "棚": ("BUNG", "Giá, kệ", "棚", "たな", "Kệ, giá"),
    "楽": ("LAC", "Vui vẻ, âm nhạc", "音楽", "おんがく", "Âm nhạc"),
    "業": ("NGHIEP", "Nghề nghiệp, công việc", "職業", "しょくぎょう", "Nghề nghiệp"),
    "様": ("DUONG", "Dáng vẻ, thể thức", "様子", "ようす", "Dáng vẻ, tình trạng"),
    "構": ("CAU", "Cấu trúc, bất kể", "構造", "こうぞう", "Cấu trúc"),
    "横": ("HOANG", "Ngang, bên cạnh", "横", "よこ", "Chiều ngang"),
    "標": ("TIEU", "Dấu hiệu, tiêu chí", "目標", "もくひょう", "Mục tiêu"),
    "橋": ("KIEU", "Cầu", "橋", "はし", "Cây cầu"),
    "機": ("CO", "Máy móc, cơ hội", "機会", "きかい", "Cơ hội"),
    "欠": ("KHUYET", "Khuyết, vắng mặt", "欠席", "けっせき", "Vắng mặt"),
    "次": ("THU", "Kế tiếp, thứ", "次第", "しだい", "Theo thứ tự"),
    "欲": ("DUC", "Dục vọng, muốn", "欲しい", "ほしい", "Muốn"),
    "歌": ("CA", "Bài hát", "歌う", "うたう", "Ca hát"),
    "止": ("CHI", "Dừng lại", "止まる", "とまる", "Dừng lại"),
    "正": ("CHINH", "Chính xác, đúng", "正しい", "ただしい", "Đúng, chính xác"),
    "歩": ("BO", "Đi bộ, bước", "散歩", "さんぽ", "Dạo bộ"),
    "歳": ("THE", "Tuổi", "年齢", "ねんれい", "Tuổi tác"),
    "歴": ("LICH", "Lịch sử, kinh nghiệm", "歴史", "れきし", "Lịch sử"),
    "死": ("TU", "Chết, tử", "死ぬ", "しぬ", "Chết"),
    "残": ("TAN", "Còn lại, tàn nhẫn", "残念", "ざんねん", "Đáng tiếc"),
    "殴": ("AU", "Đánh, đấm", "殴る", "なぐる", "Đánh, đấm"),
    "段": ("DOAN", "Bậc, đoạn", "段階", "だんかい", "Giai đoạn"),
    "殺": ("SAT", "Giết", "殺す", "ころす", "Giết"),
    "母": ("MAU", "Mẹ", "母親", "ははおや", "Người mẹ"),
    "毎": ("MAI", "Mỗi, hàng", "毎日", "まいにち", "Mỗi ngày"),
    "比": ("TY", "So sánh, tỉ", "比べる", "くらべる", "So sánh"),
    "毛": ("MAO", "Lông, tóc", "毛布", "もうふ", "Chăn len"),
    "氏": ("THI", "Họ tên, ngài", "氏名", "しめい", "Họ và tên"),
    "民": ("DAN", "Dân, người dân", "国民", "こくみん", "Quốc dân"),
    "気": ("KHI", "Khí, không khí, tinh thần", "天気", "てんき", "Thời tiết"),
    "水": ("THUY", "Nước", "水曜日", "すいようび", "Thứ Tư"),
    "氷": ("BANG", "Đá, băng", "氷", "こおり", "Đá lạnh, băng"),
    "池": ("TRI", "Ao, hồ nhỏ", "池", "いけ", "Ao"),
    "汚": ("O", "Bẩn, ô nhiễm", "汚い", "きたない", "Bẩn"),
    "汗": ("HAN", "Mồ hôi", "汗", "あせ", "Mồ hôi"),
    "決": ("QUYET", "Quyết định", "決める", "きめる", "Quyết định"),
    "求": ("CAU", "Cầu, tìm kiếm", "求める", "もとめる", "Tìm kiếm, yêu cầu"),
    "沈": ("TRAM", "Chìm, lặng", "沈む", "しずむ", "Chìm xuống"),
    "泳": ("VINH", "Bơi lội", "水泳", "すいえい", "Bơi lội"),
    "注": ("CHU", "Chú ý, rót", "注意", "ちゅうい", "Chú ý"),
    "波": ("BA", "Sóng", "波", "なみ", "Sóng"),
    "油": ("DAU", "Dầu", "石油", "せきゆ", "Dầu mỏ"),
    "泣": ("KHAP", "Khóc", "泣く", "なく", "Khóc"),
    "治": ("TRI", "Trị, điều trị", "政治", "せいじ", "Chính trị"),
    "法": ("PHAP", "Pháp luật, phương pháp", "方法", "ほうほう", "Phương pháp"),
    "泊": ("BAC", "Nghỉ ngơi, lưu trú", "宿泊", "しゅくはく", "Lưu trú"),
    "泥": ("NI", "Bùn, lầy lội", "泥棒", "どろぼう", "Tên trộm"),
    "沸": ("PHAT", "Sôi", "沸く", "わく", "Sôi"),
    "海": ("HAI", "Biển, đại dương", "海外", "かいがい", "Nước ngoài"),
    "活": ("HOAT", "Hoạt động, sống", "生活", "せいかつ", "Cuộc sống"),
    "洋": ("DUONG", "Đại dương, phương Tây", "西洋", "せいよう", "Phương Tây"),
    "泉": ("TUYEN", "Suối, nguồn", "温泉", "おんせん", "Suối nước nóng"),
    "洗": ("THIEN", "Rửa", "洗濯", "せんたく", "Giặt giũ"),
    "派": ("PHAI", "Phái, phân công", "派遣", "はけん", "Phái đi, điều phối"),
    "消": ("TIEU", "Tiêu, tắt", "消える", "きえる", "Biến mất"),
    "流": ("LUU", "Dòng chảy, trào lưu", "流れる", "ながれる", "Chảy"),
    "浴": ("DUC", "Tắm", "入浴", "にゅうよく", "Tắm"),
    "涙": ("LE", "Nước mắt", "涙", "なみだ", "Nước mắt"),
    "深": ("THAM", "Sâu", "深い", "ふかい", "Sâu"),
    "混": ("HON", "Trộn, hỗn độn", "混雑", "こんざつ", "Đông đúc, ùn tắc"),
    "済": ("TE", "Xong, kinh tế", "経済", "けいざい", "Kinh tế"),
    "涼": ("LUONG", "Mát mẻ", "涼しい", "すずしい", "Mát mẻ"),
    "温": ("ON", "Ấm, nhiệt độ", "温度", "おんど", "Nhiệt độ"),
    "湖": ("HO", "Hồ", "湖", "みずうみ", "Hồ"),
    "港": ("CANG", "Cảng, bến cảng", "空港", "くうこう", "Sân bay"),
    "湯": ("THANG", "Nước nóng, canh", "お湯", "おゆ", "Nước sôi"),
    "満": ("MAN", "Đầy, mãn", "満足", "まんぞく", "Thỏa mãn"),
    "減": ("GIAM", "Giảm", "減る", "へる", "Giảm"),
    "渡": ("DO", "Qua, vượt qua", "渡す", "わたす", "Chuyển, trao"),
    "漢": ("HAN", "Hán, đàn ông", "漢字", "かんじ", "Chữ Hán"),
    "準": ("CHUAN", "Chuẩn bị, tiêu chuẩn", "準備", "じゅんび", "Chuẩn bị"),
    "源": ("NGUYEN", "Nguồn gốc", "資源", "しげん", "Tài nguyên"),
    "溶": ("DUNG", "Tan, hòa tan", "溶ける", "とける", "Tan chảy"),
    "漁": ("NGU", "Đánh cá", "漁業", "ぎょぎょう", "Ngư nghiệp"),
    "漂": ("PIEU", "Trôi dạt", "漂う", "ただよう", "Trôi nổi"),
    "激": ("KICH", "Kịch liệt, mạnh mẽ", "激しい", "はげしい", "Mãnh liệt"),
    "濃": ("NONG", "Đậm, đặc", "濃い", "こい", "Đậm, đặc"),
    "濯": ("THUOC", "Giặt, rửa", "洗濯", "せんたく", "Giặt giũ"),
    "火": ("HOA", "Lửa", "火曜日", "かようび", "Thứ Ba"),
    "灯": ("DANG", "Đèn", "信号灯", "しんごうとう", "Đèn tín hiệu"),
    "炊": ("CHUY", "Nấu cơm", "炊事", "すいじ", "Nấu ăn"),
    "点": ("DIEM", "Điểm, chấm", "点数", "てんすう", "Điểm số"),
    "焼": ("THIEU", "Nướng, đốt", "焼く", "やく", "Nướng"),
    "然": ("NHIEN", "Nhiên, tự nhiên", "自然", "しぜん", "Tự nhiên"),
    "無": ("VO", "Vô, không có", "無理", "むり", "Vô lý, không thể"),
    "煮": ("CHU", "Nấu, đun", "煮る", "にる", "Nấu, đun"),
    "煙": ("KHOI", "Khói", "煙", "けむり", "Khói"),
    "熱": ("NHIET", "Nóng, nhiệt", "熱い", "あつい", "Nóng"),
    "燃": ("NHIEN", "Cháy", "燃える", "もえる", "Cháy"),
    "父": ("PHU", "Cha, bố", "父親", "ちちおや", "Người cha"),
    "片": ("PHIEN", "Mảnh, phiến", "片付ける", "かたづける", "Dọn dẹp"),
    "牛": ("NGUU", "Con bò", "牛乳", "ぎゅうにゅう", "Sữa bò"),
    "物": ("VAT", "Vật, đồ vật", "食べ物", "たべもの", "Đồ ăn"),
    "特": ("DAC", "Đặc biệt", "特別", "とくべつ", "Đặc biệt"),
    "犬": ("KHUYNH", "Chó", "犬", "いぬ", "Con chó"),
    "犯": ("PHAM", "Phạm tội", "犯罪", "はんざい", "Tội phạm"),
    "状": ("TRANG", "Trạng thái, thư", "状況", "じょうきょう", "Tình hình"),
    "独": ("DOC", "Độc lập, một mình", "独立", "どくりつ", "Độc lập"),
    "狭": ("HEP", "Hẹp", "狭い", "せまい", "Hẹp"),
    "猫": ("MAO", "Con mèo", "猫", "ねこ", "Con mèo"),
    "玄": ("HUYEN", "Huyền bí, tối", "玄関", "げんかん", "Cửa vào, sảnh"),
    "王": ("VUONG", "Vua, vương", "王様", "おうさま", "Vua"),
    "玉": ("NGOC", "Ngọc, hòn bi", "宝玉", "ほうぎょく", "Ngọc quý"),
    "珍": ("TRAN", "Quý hiếm, lạ", "珍しい", "めずらしい", "Hiếm, lạ"),
    "理": ("LY", "Lý, lý do", "理由", "りゆう", "Lý do"),
    "球": ("CAU", "Quả bóng, cầu", "地球", "ちきゅう", "Trái đất"),
    "現": ("HIEN", "Hiện tại, xuất hiện", "現在", "げんざい", "Hiện tại"),
    "環": ("HOAN", "Vòng, môi trường", "環境", "かんきょう", "Môi trường"),
    "甘": ("DAM", "Ngọt", "甘い", "あまい", "Ngọt"),
    "生": ("SINH", "Sống, sinh ra", "学生", "がくせい", "Học sinh"),
    "産": ("SAN", "Sản xuất, sản phẩm", "生産", "せいさん", "Sản xuất"),
    "用": ("DUNG", "Dùng, sử dụng", "使用", "しよう", "Sử dụng"),
    "田": ("DIEN", "Ruộng, điền", "田んぼ", "たんぼ", "Ruộng lúa"),
    "申": ("THAN", "Xin, khai báo", "申し込む", "もうしこむ", "Đăng ký"),
    "由": ("DO", "Do, lý do", "理由", "りゆう", "Lý do"),
    "男": ("NAM", "Nam, đàn ông", "男性", "だんせい", "Đàn ông"),
    "町": ("DINH", "Thị trấn, phường", "町", "まち", "Thị trấn"),
    "画": ("HOA", "Vẽ, bức tranh", "映画", "えいが", "Phim"),
    "界": ("GIOI", "Thế giới, giới", "世界", "せかい", "Thế giới"),
    "畑": ("THIEM", "Ruộng rẫy", "畑", "はたけ", "Rẫy, vườn"),
    "留": ("LUU", "Ở lại, lưu giữ", "留学", "りゅうがく", "Du học"),
    "畜": ("SUC", "Súc vật", "家畜", "かちく", "Gia súc"),
    "番": ("BAN", "Số thứ tự, lần", "番号", "ばんごう", "Số thứ tự"),
    "疑": ("NGHI", "Nghi ngờ", "疑問", "ぎもん", "Câu hỏi, thắc mắc"),
    "病": ("BENH", "Bệnh", "病院", "びょういん", "Bệnh viện"),
    "疲": ("BI", "Mệt mỏi", "疲れる", "つかれる", "Mệt mỏi"),
    "症": ("CHUNG", "Triệu chứng", "症状", "しょうじょう", "Triệu chứng"),
    "痛": ("THONG", "Đau", "頭痛", "ずつう", "Đau đầu"),
    "療": ("LIEU", "Điều trị", "治療", "ちりょう", "Điều trị"),
    "発": ("PHAT", "Phát, xuất phát", "出発", "しゅっぱつ", "Khởi hành"),
    "登": ("DANG", "Leo, đăng", "登山", "とざん", "Leo núi"),
    "白": ("BACH", "Trắng", "白い", "しろい", "Trắng"),
    "百": ("BACH", "Một trăm", "百円", "ひゃくえん", "Một trăm yên"),
    "的": ("DICH", "Đích, thuộc tính", "目的", "もくてき", "Mục đích"),
    "皆": ("GIAI", "Mọi người, tất cả", "皆さん", "みなさん", "Mọi người"),
    "皮": ("BI", "Da, vỏ", "皮膚", "ひふ", "Da (cơ thể)"),
    "皿": ("MINH", "Đĩa, chén", "皿", "さら", "Đĩa"),
    "盛": ("THINH", "Thịnh vượng, đầy ắp", "盛り上がる", "もりあがる", "Sôi nổi"),
    "盗": ("DAO", "Trộm cắp", "盗む", "ぬすむ", "Trộm"),
    "目": ("MOC", "Mắt", "目的", "もくてき", "Mục đích"),
    "直": ("THUC", "Thẳng, thật", "直接", "ちょくせつ", "Trực tiếp"),
    "県": ("HUYEN", "Tỉnh, huyện", "県", "けん", "Tỉnh"),
    "相": ("TUONG", "Lẫn nhau, tướng", "相談", "そうだん", "Tư vấn, thảo luận"),
    "省": ("TINH", "Tỉnh lị, tiết kiệm", "反省", "はんせい", "Phản tỉnh"),
    "看": ("KHAN", "Nhìn, chăm sóc", "看護師", "かんごし", "Y tá"),
    "真": ("CHAN", "Thật, chân thật", "真剣", "しんけん", "Nghiêm túc"),
    "眠": ("MIAN", "Ngủ", "睡眠", "すいみん", "Giấc ngủ"),
    "眼": ("NHAN", "Mắt", "眼鏡", "めがね", "Kính mắt"),
    "眺": ("TRIEU", "Nhìn ra xa", "眺める", "ながめる", "Nhìn ra xa"),
    "睡": ("THUY", "Ngủ, buồn ngủ", "睡眠", "すいみん", "Giấc ngủ"),
    "矢": ("THA", "Mũi tên", "矢", "や", "Mũi tên"),
    "知": ("TRI", "Biết, tri thức", "知識", "ちしき", "Kiến thức"),
    "短": ("DOAN", "Ngắn", "短い", "みじかい", "Ngắn"),
    "石": ("THACH", "Đá", "石", "いし", "Đá"),
    "研": ("NGHIEN", "Nghiên cứu, mài", "研究", "けんきゅう", "Nghiên cứu"),
    "砂": ("SA", "Cát", "砂", "すな", "Cát"),
    "破": ("PHA", "Vỡ, phá", "破壊", "はかい", "Phá hủy"),
    "硬": ("CUNG", "Cứng", "硬い", "かたい", "Cứng"),
    "確": ("XAC", "Xác nhận, chắc chắn", "確認", "かくにん", "Xác nhận"),
    "磨": ("MA", "Đánh bóng, mài", "磨く", "みがく", "Đánh bóng"),
    "示": ("THI", "Chỉ, cho thấy", "指示", "しじ", "Chỉ thị"),
    "礼": ("LE", "Lễ, cảm ơn", "礼儀", "れいぎ", "Lễ nghi"),
    "社": ("XA", "Công ty, xã hội", "会社", "かいしゃ", "Công ty"),
    "祈": ("KY", "Cầu nguyện", "祈る", "いのる", "Cầu nguyện"),
    "神": ("THAN", "Thần, thần thánh", "神社", "じんじゃ", "Đền Shinto"),
    "祝": ("CHUC", "Chúc mừng", "祝日", "しゅくじつ", "Ngày lễ"),
    "祖": ("TO", "Tổ tiên", "祖父", "そふ", "Ông nội/ngoại"),
    "祭": ("TE", "Lễ hội, tế lễ", "祭り", "まつり", "Lễ hội"),
    "票": ("PHIEU", "Phiếu, vé", "投票", "とうひょう", "Bỏ phiếu"),
    "福": ("PHUC", "Phúc, may mắn", "幸福", "こうふく", "Hạnh phúc"),
    "禁": ("CAM", "Cấm", "禁止", "きんし", "Cấm"),
    "秀": ("TU", "Xuất sắc, tú", "優秀", "ゆうしゅう", "Xuất sắc"),
    "科": ("KHOA", "Khoa, môn học", "科学", "かがく", "Khoa học"),
    "秋": ("THU", "Mùa thu", "秋", "あき", "Mùa thu"),
    "秒": ("GIAC", "Giây (đơn vị thời gian)", "秒", "びょう", "Giây"),
    "秘": ("BI", "Bí mật, bí", "秘密", "ひみつ", "Bí mật"),
    "移": ("DI", "Di chuyển, dời", "移動", "いどう", "Di chuyển"),
    "税": ("THUE", "Thuế", "消費税", "しょうひぜい", "Thuế tiêu thụ"),
    "程": ("TRINH", "Trình độ, mức", "程度", "ていど", "Mức độ"),
    "稚": ("CHI", "Ấu thơ, non nớt", "幼稚", "ようち", "Ấu trĩ"),
    "種": ("CHUNG", "Loài, giống", "種類", "しゅるい", "Chủng loại"),
    "稼": ("GIA", "Kiếm tiền", "稼ぐ", "かせぐ", "Kiếm tiền"),
    "積": ("TICH", "Tích lũy, diện tích", "面積", "めんせき", "Diện tích"),
    "穏": ("ON", "Êm đềm, yên tĩnh", "穏やか", "おだやか", "Êm dịu"),
    "穴": ("XUYET", "Lỗ hổng, hang", "穴", "あな", "Lỗ hổng"),
    "究": ("CUU", "Nghiên cứu", "研究", "けんきゅう", "Nghiên cứu"),
    "空": ("KHONG", "Bầu trời, rỗng", "空港", "くうこう", "Sân bay"),
    "突": ("DOT", "Đột ngột, đâm", "突然", "とつぜん", "Đột nhiên"),
    "窓": ("SONG", "Cửa sổ", "窓", "まど", "Cửa sổ"),
    "立": ("LAP", "Đứng, lập", "立場", "たちば", "Lập trường"),
    "章": ("CHUONG", "Chương, hiệu", "文章", "ぶんしょう", "Văn phong, câu văn"),
    "童": ("DONG", "Trẻ em, đồng", "児童", "じどう", "Nhi đồng"),
    "端": ("DOAN", "Đầu, mút, cực đoan", "端", "はし", "Đầu, cuối"),
    "競": ("CANH", "Cạnh tranh, thi đua", "競争", "きょうそう", "Cạnh tranh"),
    "竹": ("TRUC", "Tre, trúc", "竹", "たけ", "Cây tre"),
    "笑": ("TIEU", "Cười", "笑う", "わらう", "Cười"),
    "第": ("DE", "Thứ, đệ", "第一", "だいいち", "Thứ nhất"),
    "符": ("PHU", "Ký hiệu, dấu", "符号", "ふごう", "Ký hiệu"),
    "答": ("DAP", "Trả lời, đáp", "答える", "こたえる", "Trả lời"),
    "等": ("DANG", "Bằng nhau, hạng", "平等", "びょうどう", "Bình đẳng"),
    "筆": ("BUT", "Bút, viết", "鉛筆", "えんぴつ", "Bút chì"),
    "節": ("TIET", "Tiết, đốt", "季節", "きせつ", "Mùa, tiết"),
    "算": ("TOAN", "Tính toán, toán", "計算", "けいさん", "Tính toán"),
    "管": ("QUAN", "Ống, quản lý", "管理", "かんり", "Quản lý"),
    "箱": ("SACH", "Hộp, thùng", "箱", "はこ", "Hộp"),
    "範": ("PHAM", "Mẫu, phạm vi", "範囲", "はんい", "Phạm vi"),
    "箸": ("TRU", "Đũa", "箸", "はし", "Đũa"),
    "築": ("TRUC", "Xây dựng", "建築", "けんちく", "Kiến trúc"),
    "簡": ("GIAN", "Đơn giản, sơ lược", "簡単", "かんたん", "Đơn giản"),
    "籍": ("TICH", "Hộ tịch, quốc tịch", "国籍", "こくせき", "Quốc tịch"),
    "米": ("MY", "Gạo, Mỹ", "米国", "べいこく", "Hoa Kỳ"),
    "粉": ("PHAN", "Bột", "小麦粉", "こむぎこ", "Bột mì"),
    "粋": ("TUY", "Thuần khiết, sành điệu", "粋", "いき", "Sành điệu"),
    "粒": ("LAP", "Hạt", "粒", "つぶ", "Hạt"),
    "粧": ("TRANG", "Trang điểm", "化粧", "けしょう", "Trang điểm"),
    "精": ("TINH", "Tinh chất, tinh tế", "精神", "せいしん", "Tinh thần"),
    "糖": ("DUONG", "Đường (thực phẩm)", "砂糖", "さとう", "Đường cát"),
    "系": ("HE", "Hệ, dòng", "系統", "けいとう", "Hệ thống"),
    "級": ("CAP", "Cấp, hạng", "上級", "じょうきゅう", "Cấp cao"),
    "紀": ("KY", "Kỷ, thế kỷ", "世紀", "せいき", "Thế kỷ"),
    "約": ("UONG", "Khoảng, ước", "約束", "やくそく", "Lời hứa"),
    "紅": ("HONG", "Đỏ, hồng", "紅葉", "こうよう", "Lá đỏ mùa thu"),
    "紙": ("CHI", "Giấy", "手紙", "てがみ", "Thư"),
    "純": ("THUAN", "Thuần, trong sạch", "純粋", "じゅんすい", "Thuần khiết"),
    "納": ("NAP", "Nộp, cất", "納得", "なっとく", "Thỏa mãn, hiểu"),
    "細": ("TE", "Mỏng, chi tiết", "細い", "ほそい", "Mỏng, gầy"),
    "組": ("TO", "Tổ, nhóm", "組む", "くむ", "Lắp ghép, nhóm"),
    "終": ("CHUNG", "Kết thúc", "終わる", "おわる", "Kết thúc"),
    "経": ("KINH", "Kinh, trải qua", "経験", "けいけん", "Kinh nghiệm"),
    "紹": ("THIEU", "Giới thiệu", "紹介", "しょうかい", "Giới thiệu"),
    "給": ("CAP", "Cấp, phát", "給料", "きゅうりょう", "Lương"),
    "結": ("KET", "Kết, buộc", "結果", "けっか", "Kết quả"),
    "絶": ("TUYET", "Tuyệt, dứt", "絶対", "ぜったい", "Tuyệt đối"),
    "統": ("THONG", "Thống nhất", "伝統", "でんとう", "Truyền thống"),
    "絡": ("LAC", "Liên lạc", "連絡", "れんらく", "Liên lạc"),
    "絞": ("GAO", "Siết, vắt", "絞る", "しぼる", "Vắt, siết chặt"),
    "続": ("TUC", "Tiếp tục", "続ける", "つづける", "Tiếp tục"),
    "緑": ("LUC", "Màu xanh lá", "緑", "みどり", "Màu xanh lá"),
    "練": ("LUYEN", "Luyện tập", "練習", "れんしゅう", "Luyện tập"),
    "総": ("TONG", "Tổng, toàn bộ", "総合", "そうごう", "Tổng hợp"),
    "緒": ("TU", "Cùng nhau, đầu mối", "一緒", "いっしょ", "Cùng nhau"),
    "線": ("TUYEN", "Đường, tuyến", "新幹線", "しんかんせん", "Tàu cao tốc Shinkansen"),
    "編": ("BIEN", "Biên tập, đan", "編集", "へんしゅう", "Biên tập"),
    "緊": ("KHAN", "Khẩn cấp, căng thẳng", "緊張", "きんちょう", "Hồi hộp"),
    "締": ("DINH", "Thắt, đóng", "締め切り", "しめきり", "Hạn chót"),
    "績": ("TICH", "Thành tích", "成績", "せいせき", "Thành tích"),
    "繰": ("CUON", "Cuộn, lặp lại", "繰り返す", "くりかえす", "Lặp lại"),
    "缶": ("QUAN", "Hộp thiếc, lon", "缶", "かん", "Lon, hộp thiếc"),
    "置": ("TRI", "Đặt, để", "置く", "おく", "Đặt"),
    "罪": ("TOI", "Tội lỗi", "犯罪", "はんざい", "Tội phạm"),
    "署": ("THU", "Đồn, chữ ký", "署名", "しょめい", "Chữ ký"),
    "罰": ("PHAT", "Phạt, trừng phạt", "罰金", "ばっきん", "Tiền phạt"),
    "羊": ("DUONG", "Con cừu", "羊", "ひつじ", "Con cừu"),
    "美": ("MY", "Đẹp", "美しい", "うつくしい", "Đẹp"),
    "着": ("TRUO", "Mặc, đến nơi", "着る", "きる", "Mặc"),
    "義": ("NGHIA", "Nghĩa, đạo đức", "意義", "いぎ", "Ý nghĩa"),
    "羽": ("VU", "Lông chim, cánh", "羽根", "はね", "Cánh chim"),
    "習": ("TAP", "Học, tập", "練習", "れんしゅう", "Luyện tập"),
    "翌": ("DUC", "Hôm sau, kế tiếp", "翌日", "よくじつ", "Ngày hôm sau"),
    "翻": ("PHIEN", "Dịch, lật", "翻訳", "ほんやく", "Dịch thuật"),
    "考": ("KHAO", "Suy nghĩ, xem xét", "考える", "かんがえる", "Suy nghĩ"),
    "老": ("LAO", "Già, lão", "老人", "ろうじん", "Người già"),
    "者": ("GIA", "Người, giả", "記者", "きしゃ", "Phóng viên"),
    "耳": ("NHI", "Tai", "耳", "みみ", "Tai"),
    "聞": ("VAN", "Nghe, hỏi", "新聞", "しんぶん", "Báo chí"),
    "聴": ("THANH", "Lắng nghe", "聴く", "きく", "Lắng nghe"),
    "職": ("CHUC", "Chức vụ, nghề", "職業", "しょくぎょう", "Nghề nghiệp"),
    "肉": ("NHUC", "Thịt", "肉", "にく", "Thịt"),
    "肌": ("CU", "Da thịt", "肌", "はだ", "Da"),
    "育": ("DUC", "Nuôi dưỡng, giáo dục", "教育", "きょういく", "Giáo dục"),
    "肩": ("KIEN", "Vai (bộ phận cơ thể)", "肩", "かた", "Vai"),
    "肯": ("KHANG", "Đồng ý, khẳng định", "肯定", "こうてい", "Khẳng định"),
    "胃": ("VI", "Dạ dày", "胃", "い", "Dạ dày"),
    "肺": ("PHE", "Phổi", "肺", "はい", "Phổi"),
    "背": ("BOI", "Lưng, chiều cao", "背中", "せなか", "Lưng"),
    "能": ("NANG", "Năng lực, tài năng", "能力", "のうりょく", "Năng lực"),
    "胸": ("HUNG", "Ngực", "胸", "むね", "Ngực"),
    "脳": ("NAO", "Não", "頭脳", "ずのう", "Trí tuệ, não"),
    "脱": ("THOAT", "Thoát, cởi", "脱ぐ", "ぬぐ", "Cởi, tháo ra"),
    "腕": ("VAN", "Cánh tay, khả năng", "腕", "うで", "Cánh tay"),
    "腹": ("PHUC", "Bụng", "腹", "おなか", "Bụng"),
    "腰": ("YEU", "Hông, eo", "腰", "こし", "Hông, eo"),
    "腐": ("PHU", "Thối rữa", "豆腐", "とうふ", "Đậu phụ"),
    "臓": ("TANG", "Nội tạng", "心臓", "しんぞう", "Tim"),
    "臣": ("THAN", "Thần, bề tôi", "大臣", "だいじん", "Bộ trưởng"),
    "自": ("TU", "Tự, bản thân", "自分", "じぶん", "Bản thân"),
    "臭": ("XIU", "Hôi, mùi", "臭い", "くさい", "Hôi"),
    "興": ("HUNG", "Hứng thú, thịnh vượng", "興味", "きょうみ", "Hứng thú"),
    "舌": ("THIET", "Lưỡi", "舌", "した", "Lưỡi"),
    "舎": ("XA", "Nhà, doanh trại", "校舎", "こうしゃ", "Nhà trường"),
    "舞": ("VU", "Múa, vũ", "舞台", "ぶたい", "Sân khấu"),
    "舟": ("CHU", "Thuyền nhỏ", "舟", "ふね", "Thuyền"),
    "航": ("HANG", "Hàng hải, bay", "航空", "こうくう", "Hàng không"),
    "般": ("BAN", "Chung, loại", "一般", "いっぱん", "Nói chung"),
    "船": ("THUEN", "Thuyền, tàu", "船", "ふね", "Con tàu"),
    "良": ("LUONG", "Tốt", "良い", "よい", "Tốt"),
    "色": ("SAC", "Màu sắc", "色", "いろ", "Màu sắc"),
    "花": ("HOA", "Hoa", "花火", "はなび", "Pháo hoa"),
    "芸": ("NGHE", "Nghệ thuật", "芸術", "げいじゅつ", "Nghệ thuật"),
    "苦": ("KHO", "Khổ, đắng", "苦しい", "くるしい", "Khổ sở"),
    "英": ("ANH", "Anh (nước), xuất sắc", "英語", "えいご", "Tiếng Anh"),
    "若": ("NHUO", "Trẻ trung", "若い", "わかい", "Trẻ"),
    "草": ("THAO", "Cỏ", "草原", "そうげん", "Thảo nguyên"),
    "茶": ("TRA", "Trà", "お茶", "おちゃ", "Trà"),
    "荒": ("HOANG", "Hoang tàn, thô bạo", "荒い", "あらい", "Thô bạo"),
    "荷": ("HA", "Hàng hóa, gánh nặng", "荷物", "にもつ", "Hành lý"),
    "華": ("HOA", "Hoa, hoa lệ", "華やか", "はなやか", "Hoa lệ, lộng lẫy"),
    "菜": ("CAI", "Rau", "野菜", "やさい", "Rau củ"),
    "菓": ("QUA", "Bánh kẹo, quả", "菓子", "かし", "Bánh kẹo"),
    "葉": ("DIEP", "Lá cây", "葉", "は", "Lá cây"),
    "落": ("LAC", "Rơi, lạc", "落ちる", "おちる", "Rơi xuống"),
    "葬": ("TANG", "Tang lễ, chôn cất", "葬式", "そうしき", "Đám tang"),
    "蒸": ("TRUNG", "Hấp, bốc hơi", "蒸し暑い", "むしあつい", "Oi bức"),
    "蔵": ("TANG", "Kho, lưu giữ", "冷蔵庫", "れいぞうこ", "Tủ lạnh"),
    "薬": ("DUOC", "Thuốc", "薬局", "やっきょく", "Nhà thuốc"),
    "薄": ("BAC", "Mỏng, nhạt", "薄い", "うすい", "Mỏng, nhạt"),
    "虫": ("TRUNG", "Côn trùng, sâu bọ", "虫", "むし", "Côn trùng"),
    "虹": ("HONG", "Cầu vồng", "虹", "にじ", "Cầu vồng"),
    "蚊": ("VAN", "Muỗi", "蚊", "か", "Con muỗi"),
    "蛍": ("HUYEN", "Con đom đóm", "蛍", "ほたる", "Con đom đóm"),
    "蛇": ("XA", "Rắn", "蛇", "へび", "Con rắn"),
    "蜂": ("PHONG", "Con ong", "蜂蜜", "はちみつ", "Mật ong"),
    "蜜": ("MAT", "Mật ong, ngọt ngào", "蜂蜜", "はちみつ", "Mật ong"),
    "血": ("HUYET", "Máu", "血液", "けつえき", "Máu"),
    "行": ("HANH", "Đi, hành", "旅行", "りょこう", "Du lịch"),
    "術": ("THUAT", "Thuật, kỹ thuật", "技術", "ぎじゅつ", "Kỹ thuật"),
    "街": ("GAI", "Đường phố, phố", "街", "まち", "Phố"),
    "衣": ("Y", "Quần áo, y phục", "衣服", "いふく", "Quần áo"),
    "表": ("BIEU", "Bảng, bề mặt, biểu", "表現", "ひょうげん", "Biểu hiện"),
    "被": ("BI", "Bị, chịu đựng", "被害", "ひがい", "Thiệt hại"),
    "袋": ("DAI", "Túi, bao", "袋", "ふくろ", "Túi, bao"),
    "裏": ("LY", "Mặt sau, bên trong", "裏口", "うらぐち", "Cửa sau"),
    "製": ("CHE", "Chế tạo, sản xuất", "製品", "せいひん", "Sản phẩm"),
    "複": ("PHUC", "Phức tạp, nhiều", "複雑", "ふくざつ", "Phức tạp"),
    "西": ("TAY", "Tây, phía tây", "西洋", "せいよう", "Phương Tây"),
    "要": ("YEU", "Quan trọng, yêu cầu", "必要", "ひつよう", "Cần thiết"),
    "見": ("KIEN", "Nhìn, thấy", "意見", "いけん", "Ý kiến"),
    "規": ("QUY", "Quy tắc, luật", "規則", "きそく", "Quy tắc"),
    "視": ("THI", "Nhìn, xem", "視点", "してん", "Quan điểm"),
    "覚": ("GIAC", "Cảm giác, nhớ", "覚える", "おぼえる", "Nhớ"),
    "親": ("THAN", "Cha mẹ, thân thiết", "親切", "しんせつ", "Tử tế"),
    "覧": ("LAM", "Xem, duyệt", "一覧", "いちらん", "Danh sách"),
    "観": ("QUAN", "Quan sát, cảnh", "観光", "かんこう", "Du lịch, tham quan"),
    "角": ("GIAC", "Góc, sừng", "角", "かど", "Góc"),
    "解": ("GIAI", "Giải, hiểu", "理解", "りかい", "Hiểu"),
    "触": ("XUC", "Chạm, tiếp xúc", "触れる", "ふれる", "Chạm vào"),
    "言": ("NGON", "Nói, lời nói", "言葉", "ことば", "Ngôn ngữ, lời nói"),
    "計": ("KE", "Kế hoạch, tính toán", "計画", "けいかく", "Kế hoạch"),
    "記": ("KY", "Ghi chép, ký", "記録", "きろく", "Ghi chép, kỷ lục"),
    "訓": ("HUAN", "Huấn luyện, âm Nhật", "訓練", "くんれん", "Huấn luyện"),
    "許": ("HUA", "Cho phép", "許可", "きょか", "Cho phép"),
    "設": ("THIET", "Thiết lập, cơ sở", "設備", "せつび", "Thiết bị"),
    "訪": ("PHONG", "Thăm, ghé thăm", "訪問", "ほうもん", "Thăm"),
    "訳": ("DICH", "Dịch, lý do", "翻訳", "ほんやく", "Dịch thuật"),
    "証": ("CHUNG", "Chứng minh, bằng chứng", "証明", "しょうめい", "Chứng minh"),
    "詞": ("TU", "Từ ngữ", "動詞", "どうし", "Động từ"),
    "診": ("CHAN", "Khám bệnh", "診断", "しんだん", "Chẩn đoán"),
    "話": ("THOAI", "Câu chuyện, nói", "電話", "でんわ", "Điện thoại"),
    "試": ("THI", "Thử, thi", "試験", "しけん", "Kỳ thi"),
    "誠": ("THANH", "Thành thật", "誠実", "せいじつ", "Thành thật"),
    "詰": ("KHE", "Chặt, dồn", "詰める", "つめる", "Nhồi vào, dồn"),
    "詳": ("TUONG", "Chi tiết", "詳しい", "くわしい", "Chi tiết, tường tận"),
    "語": ("NGU", "Ngôn ngữ, nói", "外国語", "がいこくご", "Tiếng nước ngoài"),
    "読": ("DOC", "Đọc", "読む", "よむ", "Đọc"),
    "説": ("THUYET", "Thuyết, giải thích", "説明", "せつめい", "Giải thích"),
    "評": ("BINH", "Bình luận, đánh giá", "評価", "ひょうか", "Đánh giá"),
    "誤": ("NGO", "Sai lầm, nhầm", "誤解", "ごかい", "Hiểu lầm"),
    "誌": ("CHI", "Tạp chí", "雑誌", "ざっし", "Tạp chí"),
    "認": ("NHAN", "Nhận ra, thừa nhận", "認める", "みとめる", "Thừa nhận"),
    "誘": ("DU", "Rủ, dụ dỗ", "誘う", "さそう", "Mời, rủ"),
    "談": ("DAM", "Nói chuyện, đàm thoại", "相談", "そうだん", "Tư vấn, bàn bạc"),
    "調": ("DIEU", "Điều chỉnh, nghiên cứu", "調査", "ちょうさ", "Điều tra"),
    "課": ("KHOA", "Bài học, khoa", "課題", "かだい", "Bài tập, nhiệm vụ"),
    "諸": ("CHU", "Các, mọi", "諸問題", "しょもんだい", "Các vấn đề"),
    "誕": ("DAN", "Sinh ra", "誕生日", "たんじょうび", "Sinh nhật"),
    "論": ("LUAN", "Luận, bàn luận", "議論", "ぎろん", "Tranh luận"),
    "請": ("THANH", "Yêu cầu, thỉnh", "申請", "しんせい", "Đăng ký, xin"),
    "誰": ("TAI", "Ai", "誰", "だれ", "Ai"),
    "諦": ("THE", "Chịu, từ bỏ", "諦める", "あきらめる", "Từ bỏ"),
    "講": ("GIANG", "Giảng, khoá học", "講義", "こうぎ", "Bài giảng"),
    "謝": ("TA", "Xin lỗi, cảm ơn", "謝罪", "しゃざい", "Xin lỗi"),
    "謙": ("KHIEM", "Khiêm tốn", "謙虚", "けんきょ", "Khiêm tốn"),
    "識": ("THUC", "Nhận thức, kiến thức", "知識", "ちしき", "Kiến thức"),
    "警": ("CANH", "Cảnh báo, cảnh sát", "警察", "けいさつ", "Cảnh sát"),
    "議": ("NGHI", "Nghị, thảo luận", "会議", "かいぎ", "Cuộc họp"),
    "護": ("HO", "Bảo vệ, hộ", "保護", "ほご", "Bảo vệ"),
    "譲": ("NHUONG", "Nhường, nhượng", "譲る", "ゆずる", "Nhường"),
    "谷": ("COC", "Thung lũng", "谷", "たに", "Thung lũng"),
    "豆": ("DAU", "Đậu, đỗ", "大豆", "だいず", "Đậu nành"),
    "豊": ("PHONG", "Phong phú", "豊か", "ゆたか", "Phong phú, giàu có"),
    "豚": ("HON", "Lợn", "豚肉", "ぶたにく", "Thịt lợn"),
    "象": ("TUONG", "Hình tượng, voi", "象", "ぞう", "Con voi"),
    "貝": ("BOI", "Con sò, vỏ sò", "貝", "かい", "Con sò"),
    "負": ("PHU", "Thua, gánh nặng", "勝負", "しょうぶ", "Trận đấu, thắng thua"),
    "財": ("TAI", "Tài sản, tiền bạc", "財産", "ざいさん", "Tài sản"),
    "貨": ("HOA", "Hàng hóa, tiền", "貨物", "かもつ", "Hàng hóa"),
    "責": ("TRACH", "Trách nhiệm", "責任", "せきにん", "Trách nhiệm"),
    "貧": ("BAN", "Nghèo", "貧しい", "まずしい", "Nghèo khổ"),
    "販": ("PHAN", "Bán hàng", "販売", "はんばい", "Bán hàng"),
    "買": ("MAI", "Mua", "買う", "かう", "Mua"),
    "貯": ("TRU", "Để dành, tích lũy", "貯金", "ちょきん", "Tiết kiệm"),
    "費": ("PHI", "Chi phí, tốn", "費用", "ひよう", "Chi phí"),
    "貸": ("TAI", "Cho mượn", "貸す", "かす", "Cho mượn"),
    "貴": ("QUY", "Quý giá, cao quý", "貴重", "きちょう", "Quý giá"),
    "貼": ("THIEM", "Dán, đính", "貼る", "はる", "Dán"),
    "貿": ("MAU", "Thương mại", "貿易", "ぼうえき", "Thương mại"),
    "資": ("TU", "Tài nguyên, vốn", "資料", "しりょう", "Tài liệu"),
    "賃": ("TAN", "Tiền thuê", "賃金", "ちんぎん", "Tiền lương"),
    "賞": ("THUONG", "Giải thưởng", "賞", "しょう", "Giải thưởng"),
    "賛": ("TOAN", "Tán thành, ủng hộ", "賛成", "さんせい", "Tán thành"),
    "質": ("CHAT", "Chất lượng, hỏi", "品質", "ひんしつ", "Chất lượng"),
    "賢": ("HIEN", "Thông minh, khôn ngoan", "賢い", "かしこい", "Thông minh"),
    "贈": ("TANG", "Tặng quà", "贈り物", "おくりもの", "Quà tặng"),
    "赤": ("XICH", "Đỏ", "赤い", "あかい", "Đỏ"),
    "走": ("TAU", "Chạy", "走る", "はしる", "Chạy"),
    "起": ("KHOI", "Dậy, bắt đầu", "起きる", "おきる", "Thức dậy"),
    "越": ("VIET", "Vượt qua", "越える", "こえる", "Vượt qua"),
    "趣": ("THU", "Thú vị, sở thích", "趣味", "しゅみ", "Sở thích"),
    "足": ("TUC", "Chân, đủ", "足りる", "たりる", "Đủ"),
    "路": ("LO", "Đường, con đường", "道路", "どうろ", "Đường"),
    "踊": ("DUNG", "Nhảy múa", "踊る", "おどる", "Nhảy múa"),
    "踏": ("DAP", "Dẫm, đạp", "踏む", "ふむ", "Dẫm lên"),
    "蹴": ("TUC", "Đá (bóng)", "蹴る", "ける", "Đá"),
    "身": ("THAN", "Thân thể, bản thân", "身体", "しんたい", "Thân thể"),
    "車": ("XA", "Xe", "自動車", "じどうしゃ", "Xe ô tô"),
    "軍": ("QUAN", "Quân đội", "軍隊", "ぐんたい", "Quân đội"),
    "軒": ("KHEN", "Mái hiên, đơn vị nhà", "一軒", "いっけん", "Một ngôi nhà"),
    "転": ("CHUYEN", "Lăn, chuyển", "転ぶ", "ころぶ", "Ngã"),
    "軟": ("NHAN", "Mềm", "軟らかい", "やわらかい", "Mềm"),
    "軽": ("KHINH", "Nhẹ", "軽い", "かるい", "Nhẹ"),
    "載": ("TAI", "Chở, đăng tải", "掲載", "けいさい", "Đăng tải"),
    "輪": ("LUAN", "Vòng, bánh xe", "車輪", "しゃりん", "Bánh xe"),
    "輩": ("BAI", "Bề trên/dưới, đồng hạng", "先輩", "せんぱい", "Đàn anh"),
    "輸": ("VAN", "Vận chuyển", "輸入", "ゆにゅう", "Nhập khẩu"),
    "辛": ("TAN", "Cay, cực khổ", "辛い", "からい", "Cay"),
    "辞": ("TU", "Từ chối, từ điển", "辞書", "じしょ", "Từ điển"),
    "農": ("NONG", "Nông nghiệp", "農業", "のうぎょう", "Nông nghiệp"),
    "辺": ("BIEN", "Xung quanh, bên", "辺り", "あたり", "Xung quanh"),
    "近": ("CAN", "Gần", "近い", "ちかい", "Gần"),
    "返": ("HOI", "Trả lại, quay lại", "返す", "かえす", "Trả lại"),
    "迎": ("NGHINH", "Đón, chào đón", "迎える", "むかえる", "Đón"),
    "送": ("TONG", "Gửi, tiễn", "送る", "おくる", "Gửi"),
    "追": ("TRUY", "Đuổi theo, truy", "追う", "おう", "Đuổi theo"),
    "退": ("THOAI", "Rút lui, thoái", "引退", "いんたい", "Về hưu, giải nghệ"),
    "迷": ("MAI", "Lạc đường, bối rối", "迷う", "まよう", "Lạc đường"),
    "逃": ("DAO", "Trốn chạy", "逃げる", "にげる", "Bỏ trốn"),
    "通": ("THONG", "Thông, qua", "交通", "こうつう", "Giao thông"),
    "速": ("TOC", "Nhanh, tốc độ", "速い", "はやい", "Nhanh"),
    "連": ("LIEN", "Liên kết, đưa đi", "連絡", "れんらく", "Liên lạc"),
    "造": ("TAO", "Tạo ra, xây dựng", "製造", "せいぞう", "Sản xuất, chế tạo"),
    "途": ("DO", "Đường, giữa chừng", "途中", "とちゅう", "Giữa đường"),
    "週": ("TUAN", "Tuần", "今週", "こんしゅう", "Tuần này"),
    "進": ("TIEN", "Tiến lên, tiến bộ", "進む", "すすむ", "Tiến lên"),
    "道": ("DAO", "Đường, đạo", "道路", "どうろ", "Đường"),
    "運": ("VAN", "Vận may, vận chuyển", "運動", "うんどう", "Vận động"),
    "遊": ("DU", "Chơi, du hí", "遊ぶ", "あそぶ", "Chơi"),
    "達": ("DAT", "Đạt, bạn bè", "友達", "ともだち", "Bạn bè"),
    "過": ("QUA", "Qua, vượt qua", "過去", "かこ", "Quá khứ"),
    "遅": ("TRI", "Chậm trễ", "遅い", "おそい", "Chậm"),
    "遠": ("VIEN", "Xa", "遠い", "とおい", "Xa"),
    "適": ("THICH", "Thích hợp, phù hợp", "適当", "てきとう", "Phù hợp"),
    "遭": ("TAO", "Gặp, chạm trán", "遭遇", "そうぐう", "Gặp gỡ ngẫu nhiên"),
    "選": ("TUYEN", "Chọn, tuyển", "選択", "せんたく", "Lựa chọn"),
    "避": ("BI", "Tránh né", "回避", "かいひ", "Né tránh"),
    "邪": ("XA", "Tà, xấu xa", "邪魔", "じゃま", "Cản trở"),
    "郎": ("LANG", "Chàng trai, con trai", "太郎", "たろう", "Taro"),
    "郊": ("GIAO", "Ngoại ô", "郊外", "こうがい", "Ngoại ô"),
    "都": ("DO", "Thủ đô, đô thị", "都市", "とし", "Đô thị"),
    "部": ("BO", "Bộ phận, phòng ban", "部分", "ぶぶん", "Bộ phận"),
    "郷": ("HUONG", "Quê hương", "故郷", "こきょう", "Quê hương"),
    "郵": ("BUU", "Bưu điện, bưu chính", "郵便", "ゆうびん", "Bưu chính"),
    "酒": ("TUU", "Rượu", "日本酒", "にほんしゅ", "Rượu sake"),
    "配": ("PHAI", "Phân phối, lo lắng", "配達", "はいたつ", "Giao hàng"),
    "酔": ("TUY", "Say (rượu)", "酔う", "よう", "Say rượu"),
    "酢": ("TU", "Giấm", "酢", "す", "Giấm"),
    "重": ("TRONG", "Nặng, quan trọng", "重要", "じゅうよう", "Quan trọng"),
    "野": ("DA", "Đồng quê, dã", "野菜", "やさい", "Rau củ"),
    "量": ("LUONG", "Số lượng", "量", "りょう", "Số lượng"),
    "金": ("KIM", "Vàng, tiền, kim loại", "金曜日", "きんようび", "Thứ Sáu"),
    "針": ("CHAM", "Kim (khâu), mũi kim", "針", "はり", "Kim, mũi kim"),
    "釣": ("DIEU", "Câu cá", "釣り", "つり", "Câu cá"),
    "鉄": ("SAT", "Sắt, thép", "鉄道", "てつどう", "Đường sắt"),
    "鈴": ("LINH", "Chuông nhỏ, cái chuông", "鈴", "すず", "Chuông nhỏ"),
    "銀": ("NGAN", "Bạc, ngân", "銀行", "ぎんこう", "Ngân hàng"),
    "銭": ("TIEN", "Tiền, đồng xu", "お金", "おかね", "Tiền"),
    "録": ("LUC", "Ghi chép, thu âm", "録音", "ろくおん", "Thu âm"),
    "錠": ("LONG", "Khóa, viên thuốc", "錠前", "じょうまえ", "Ổ khóa"),
    "鍵": ("KIEN", "Chìa khóa", "鍵", "かぎ", "Chìa khóa"),
    "長": ("TRUONG", "Dài, trưởng", "長い", "ながい", "Dài"),
    "門": ("MON", "Cổng, môn", "専門", "せんもん", "Chuyên môn"),
    "閉": ("BI", "Đóng", "閉める", "しめる", "Đóng"),
    "間": ("GIAN", "Khoảng, phòng", "時間", "じかん", "Thời gian"),
    "開": ("KHAI", "Mở", "開ける", "あける", "Mở"),
    "関": ("QUAN", "Liên quan, quan", "関係", "かんけい", "Quan hệ"),
    "閣": ("CAC", "Nội các, gác", "内閣", "ないかく", "Nội các"),
    "闘": ("DAU", "Đấu tranh", "戦闘", "せんとう", "Chiến đấu"),
    "防": ("PHONG", "Phòng thủ, ngăn", "防ぐ", "ふせぐ", "Ngăn chặn"),
    "阪": ("BAN", "Osaka (tên địa danh)", "大阪", "おおさか", "Osaka"),
    "降": ("HA", "Xuống, rơi", "降りる", "おりる", "Xuống (xe)"),
    "限": ("HAN", "Giới hạn", "限る", "かぎる", "Giới hạn"),
    "院": ("VIEN", "Viện, bệnh viện", "病院", "びょういん", "Bệnh viện"),
    "除": ("TRU", "Trừ, loại bỏ", "削除", "さくじょ", "Xóa bỏ"),
    "陸": ("LUC", "Đất liền, lục", "陸地", "りくち", "Đất liền"),
    "険": ("HIEM", "Nguy hiểm, hiểm", "危険", "きけん", "Nguy hiểm"),
    "階": ("GIAI", "Tầng, bậc", "階段", "かいだん", "Cầu thang"),
    "陽": ("DUONG", "Dương, mặt trời", "太陽", "たいよう", "Mặt trời"),
    "隅": ("NGU", "Góc, xó", "隅", "すみ", "Góc"),
    "際": ("TE", "Lúc, khi, biên giới", "実際", "じっさい", "Thực tế"),
    "障": ("CHONG", "Chướng ngại, rào cản", "障害", "しょうがい", "Khuyết tật, rào cản"),
    "隠": ("AN", "Ẩn náu, giấu", "隠れる", "かくれる", "Ẩn náu"),
    "隣": ("LAN", "Hàng xóm, bên cạnh", "隣", "となり", "Hàng xóm"),
    "集": ("TAP", "Tập hợp, thu thập", "集める", "あつめる", "Thu thập"),
    "雇": ("CO", "Thuê, mướn", "雇用", "こよう", "Thuê mướn"),
    "雑": ("TAP", "Tạp, lộn xộn", "雑誌", "ざっし", "Tạp chí"),
    "難": ("NAN", "Khó khăn, nạn", "困難", "こんなん", "Khó khăn"),
    "離": ("LY", "Ly, tách rời", "離れる", "はなれる", "Tách rời, xa cách"),
    "雨": ("VU", "Mưa", "雨", "あめ", "Mưa"),
    "雪": ("TUYET", "Tuyết", "雪", "ゆき", "Tuyết"),
    "雲": ("VAN", "Mây", "雲", "くも", "Mây"),
    "雰": ("PHON", "Không khí, bầu không khí", "雰囲気", "ふんいき", "Bầu không khí"),
    "電": ("DIEN", "Điện", "電話", "でんわ", "Điện thoại"),
    "雷": ("LEI", "Sấm, tia sét", "雷", "かみなり", "Sấm sét"),
    "震": ("CHAN", "Rung chuyển, địa chấn", "地震", "じしん", "Động đất"),
    "青": ("THANH", "Xanh lam/lá", "青い", "あおい", "Xanh"),
    "静": ("TINH", "Yên tĩnh", "静かな", "しずかな", "Yên tĩnh"),
    "非": ("PHI", "Phi, không phải", "非常", "ひじょう", "Khẩn cấp, phi thường"),
    "面": ("DIEN", "Mặt, bề mặt", "面白い", "おもしろい", "Thú vị"),
    "革": ("CACH", "Da, cách mạng", "革命", "かくめい", "Cách mạng"),
    "靴": ("HUE", "Giày", "靴", "くつ", "Giày"),
    "韓": ("HAN", "Hàn Quốc", "韓国", "かんこく", "Hàn Quốc"),
    "音": ("AM", "Âm thanh", "音楽", "おんがく", "Âm nhạc"),
    "響": ("HUONG", "Vang vọng, ảnh hưởng", "影響", "えいきょう", "Ảnh hưởng"),
    "頂": ("DINH", "Đỉnh, nhận (kính ngữ)", "頂上", "ちょうじょう", "Đỉnh"),
    "頃": ("KHUNG", "Khoảng, thời gian", "頃", "ごろ", "Khoảng"),
    "順": ("THUAN", "Thuận, thứ tự", "順番", "じゅんばん", "Thứ tự"),
    "預": ("THA", "Gửi, gởi giữ", "預ける", "あずける", "Gửi (tiền)"),
    "頑": ("VAN", "Cứng đầu, kiên trì", "頑張る", "がんばる", "Cố gắng"),
    "領": ("LANH", "Lãnh thổ, lãnh đạo", "領土", "りょうど", "Lãnh thổ"),
    "頭": ("DAU", "Đầu", "頭", "あたま", "Đầu"),
    "頼": ("LAI", "Nhờ vả, tin cậy", "頼む", "たのむ", "Nhờ, yêu cầu"),
    "顔": ("NHAN", "Khuôn mặt", "顔", "かお", "Khuôn mặt"),
    "題": ("DE", "Đề tài, tiêu đề", "問題", "もんだい", "Vấn đề"),
    "類": ("LOAI", "Loại, chủng loại", "種類", "しゅるい", "Chủng loại"),
    "額": ("NGACH", "Số tiền, trán", "金額", "きんがく", "Số tiền"),
    "願": ("NGUYEN", "Nguyện vọng, xin", "願う", "ねがう", "Cầu xin, mong muốn"),
    "風": ("PHONG", "Gió, phong cách", "台風", "たいふう", "Bão"),
    "飛": ("PHI", "Bay", "飛ぶ", "とぶ", "Bay"),
    "食": ("THUC", "Ăn, thực phẩm", "食べ物", "たべもの", "Đồ ăn"),
    "飲": ("AM", "Uống", "飲み物", "のみもの", "Đồ uống"),
    "飯": ("PHAN", "Cơm, bữa ăn", "ご飯", "ごはん", "Cơm"),
    "飼": ("TU", "Nuôi (thú)", "飼う", "かう", "Nuôi"),
    "飾": ("SUC", "Trang trí", "装飾", "そうしょく", "Trang trí"),
    "飽": ("BAO", "No, chán", "飽きる", "あきる", "Chán"),
    "養": ("DUONG", "Nuôi dưỡng", "栄養", "えいよう", "Dinh dưỡng"),
    "餌": ("NHI", "Mồi, thức ăn thú", "餌", "えさ", "Thức ăn (cho thú)"),
    "餅": ("BINH", "Bánh dày, bánh gạo", "お餅", "おもち", "Bánh mochi"),
    "館": ("QUAN", "Tòa nhà, quán", "図書館", "としょかん", "Thư viện"),
    "首": ("THU", "Cổ, đầu, thủ", "首都", "しゅと", "Thủ đô"),
    "香": ("HUONG", "Mùi thơm, hương", "香り", "かおり", "Hương thơm"),
    "馬": ("MA", "Ngựa", "馬", "うま", "Con ngựa"),
    "駅": ("DICH", "Nhà ga", "駅", "えき", "Nhà ga"),
    "駆": ("KHU", "Phi ngựa, chạy", "駆ける", "かける", "Chạy, phi nước đại"),
    "駄": ("TA", "Vô ích, xấu", "無駄", "むだ", "Vô ích, lãng phí"),
    "駐": ("TRU", "Đỗ xe, trú đóng", "駐車", "ちゅうしゃ", "Đỗ xe"),
    "験": ("NGHIEM", "Kinh nghiệm, thử nghiệm", "経験", "けいけん", "Kinh nghiệm"),
    "騒": ("TANH", "Ồn ào, náo loạn", "騒ぐ", "さわぐ", "Ồn ào"),
    "驚": ("KINH", "Ngạc nhiên", "驚く", "おどろく", "Ngạc nhiên"),
    "骨": ("COT", "Xương", "骨", "ほね", "Xương"),
    "高": ("CAO", "Cao", "高い", "たかい", "Cao"),
    "髪": ("PHAT", "Tóc", "髪", "かみ", "Tóc"),
    "鬼": ("QUY", "Quỷ, yêu ma", "鬼", "おに", "Quỷ"),
    "魂": ("HON", "Hồn, linh hồn", "魂", "たましい", "Linh hồn"),
    "魅": ("MY", "Mê hoặc", "魅力", "みりょく", "Sức hút, quyến rũ"),
    "魔": ("MA", "Ma, phép thuật", "悪魔", "あくま", "Ác quỷ"),
    "魚": ("NGU", "Cá", "魚", "さかな", "Con cá"),
    "鮮": ("TUOI", "Tươi, tươi mới", "新鮮", "しんせん", "Tươi"),
    "鳥": ("DIEU", "Chim", "鳥", "とり", "Con chim"),
    "鳴": ("MINH", "Kêu, tiếng kêu", "鳴く", "なく", "Kêu (chim, thú)"),
    "麦": ("MACH", "Lúa mì", "小麦", "こむぎ", "Lúa mì"),
    "黄": ("HOANG", "Màu vàng", "黄色", "きいろ", "Màu vàng"),
    "黒": ("HOC", "Đen", "黒い", "くろい", "Đen"),
    "黙": ("MUC", "Im lặng", "沈黙", "ちんもく", "Im lặng"),
    "鼻": ("TY", "Mũi", "鼻", "はな", "Mũi"),
    "歯": ("CHIA", "Răng", "歯医者", "はいしゃ", "Nha sĩ"),
    "齢": ("LINH", "Tuổi tác", "年齢", "ねんれい", "Tuổi tác"),
    "竜": ("LONG", "Rồng", "竜", "りゅう", "Rồng"),
    "亀": ("QUY", "Rùa", "亀", "かめ", "Con rùa"),
}
